Код создавался на основе: https://github.com/dhanajitb/GAIN-Pytorch/tree/master

In [ ]:
import sklearn

In [ ]:
import pandas as pd
import numpy as np
import json
from sklearn.impute import SimpleImputer
from sklearn.metrics import root_mean_squared_error as rmse, f1_score as f1, accuracy_score as acc, precision_score as pr, recall_score as rc, mean_squared_error as mse
import math

In [ ]:
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
# df_mis = pd.read_json('https://raw.githubusercontent.com/KSTSV/diploma/refs/heads/main/data01.json')
# df_tar = pd.read_json('https://raw.githubusercontent.com/KSTSV/diploma/refs/heads/main/data01_tar.json')

In [ ]:
# dfm1 = pd.DataFrame(df_mis.loc[2].to_dict())
# dft1 = pd.DataFrame(df_tar.loc[2].to_dict())


# dfm1 = dfm1[sorted(dfm1.columns)]
# dft1 = dft1[sorted(dfm1.columns)]

In [ ]:
for i in range(5, 6):
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar_.json'

In [ ]:
data_mis = pd.read_json(file_mis)
data_tar =  pd.read_json(file_tar)

dfm1 = pd.DataFrame(data_mis.loc[1].to_dict())
dft1 = pd.DataFrame(data_tar.loc[1].to_dict())

dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

# dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1)
# dfm = dfm[sorted(dft1.columns)]
# dfm

dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1)
dfm = dfm[sorted(dft1.columns)]
dfm

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,8.0,NaN,NaN,3.0,3.0,2.0,3.0,1,4.0,...,4.0,4.0,4.0,2.0,2.0,2.0,NaN,49300.0,3.0,NaN
1,44.0,39.0,NaN,8.0,5.0,6.0,6.0,7.0,2,6.0,...,7.0,7.0,7.0,6.0,8.0,7.0,NaN,219833.0,6.0,NaN
2,29.0,13.0,2.0,NaN,3.0,3.0,3.0,3.0,1,5.0,...,4.0,4.0,5.0,3.0,3.0,3.0,NaN,74772.0,4.0,1.0
3,36.0,25.0,NaN,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,5.0,3.0,130721.0,5.0,NaN
4,28.0,9.0,2.0,NaN,3.0,3.0,3.0,3.0,1,4.0,...,4.0,4.0,4.0,2.0,3.0,2.0,2.0,58085.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,33.0,20.0,NaN,7.0,4.0,4.0,4.0,4.0,1,5.0,...,5.0,5.0,5.0,4.0,4.0,4.0,6.0,107060.0,5.0,NaN
251,36.0,25.0,3.0,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,5.0,NaN,130122.0,5.0,NaN
252,28.0,11.0,NaN,NaN,3.0,3.0,3.0,3.0,1,5.0,...,4.0,4.0,4.0,2.0,3.0,2.0,2.0,65887.0,4.0,NaN
253,36.0,26.0,NaN,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,5.0,5.0,5.0,3.0,133560.0,5.0,NaN
254,35.0,24.0,NaN,7.0,4.0,4.0,4.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,4.0,3.0,122581.0,5.0,NaN

In [ ]:
cat_cols = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk']

ord_cols = ['edu', 'change_sal',
       'title_wrk', 'incm']

cat_ord = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_ord = ['agea', 'agewrk', 'fctr_succ1', 'fctr_succ2', 'fctr_succ3',
       'fctr_succ4', 'impmot1', 'impmot2', 'impmot3', 'impmot4', 'impmot5',
       'impmot6', 'impmot7', 'impmot8', 'impmot9', 'mot1', 'mot10', 'mot11',
       'mot12', 'mot13', 'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6',
       'mot7', 'mot8', 'mot9', 'num_crs', 'plcwrk', 'sal', 'sat_wrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_cols = dfm1.drop(cat_cols, axis=1).drop(ord_cols, axis=1).columns


miss_vars= ["marital_stat", "num_crs",
            "mot1", "mot2", "mot3", "mot4", "mot5", "mot6", "mot7", "mot8", "mot9", "mot10", "mot11", "mot12", "mot13", "mot14",
            "edu", "agewrk", "plcwrk", "profwrk", "change_sal", "title_wrk", "sal", "sat_wrk",
            "fctr_succ1", "fctr_succ2", "fctr_succ3", "fctr_succ4",
            "impmot1", "impmot2", "impmot3", "impmot4", "impmot5", "impmot6", "impmot7", "impmot8", "impmot9",
            "agea", "incm"]


mcar = ["marital_stat", "num_crs",
        "mot2", "mot6", "mot9", "mot10", "mot11", "mot12", "mot13",
        "agewrk", "plcwrk", "sat_wrk",
        "fctr_succ3", "fctr_succ4",
        "impmot1", "impmot4", "impmot5", "impmot8", "agea", "incm", "title_wrk"]

mar = ["mot1", "mot3", "mot4", "mot5", "mot7", "mot8", "mot14",
       "edu", "profwrk", "change_sal", "sal", "fctr_succ1",
       "fctr_succ2", "impmot2", "impmot3", "impmot6", "impmot7", "impmot9"]


mcar_cat = ['marital_stat']
mcar_ord = ['incm', 'title_wrk']
mcar_int = ['mot2', 'agea', 'mot9', 'fctr_succ4',
            'mot6', 'mot10', 'mot11', 'mot12', 'mot13',
            'impmot1', 'incm', 'impmot4', 'impmot8', 'fctr_succ3', 'agewrk',
            'plcwrk', 'sat_wrk', 'impmot5', 'num_crs']



mar_int = ['impmot2', 'impmot7', 'mot1', 'mot14', 'impmot6', 'mot7', 'mot3', 'fctr_succ2', 'impmot3', 'mot8', 'mot4', 'impmot9', 'mot5', 'sal', 'fctr_succ1']
mar_cat = ['profwrk']
mar_ord = ['edu', 'change_sal']


not_mis = ['gndr', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'money_what_employer', 'money_what_free_other', 'money_what_persona']


mis_cat_ord = ['marital_stat', 'incm', 'title_wrk', 'profwrk', 'edu', 'change_sal']

In [ ]:
cols = ['%', 'agea', 'agewrk', 'change_sal', 'edu', 'fctr_succ1', 'fctr_succ2',
       'fctr_succ3', 'fctr_succ4', 'gndr', 'impmot1', 'impmot2', 'impmot3',
       'impmot4', 'impmot5', 'impmot6', 'impmot7', 'impmot8', 'impmot9',
       'incm', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'marital_stat', 'money_what_employer', 'money_what_free_other',
       'money_what_persona', 'mot1', 'mot10', 'mot11', 'mot12', 'mot13',
       'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6', 'mot7', 'mot8', 'mot9',
       'num_crs', 'plcwrk', 'profwrk', 'sal', 'sat_wrk', 'title_wrk']


# df = pd.DataFrame(columns = cols)
df = pd.DataFrame()




cols1 = ['%', 'total_rmse', 'total_acc_ord', 'total_f1_ord', 'total_pr_ord', 'total_rc_ord', 'total_acc_cat',
        'total_f1_cat', 'total_pr_cat', 'total_rc_cat']


# df_total = pd.DataFrame(columns = cols1)
df_total = pd.DataFrame()

# GAIN

In [ ]:
from sklearn.preprocessing import StandardScaler
import torch
import numpy as np
from tqdm import tqdm
import torch.nn.functional as F

In [ ]:
def GAIN (dft1, dfm1, int_cols, mb_size, p_hint, alpha, train_rate):
  train_loss = []
  tst_loss = []
    #%% Data
  # dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1) # для интервальных данных
  dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1) # для категориальных данных
  dfm = dfm[sorted(dft1.columns)]

  # данные
  Data = np.array(dft1)

  # параметры
  No = len(Data)
  Dim = len(Data[0,:])

  # Hidden state dimensions
  H_Dim1 = Dim
  H_Dim2 = Dim

  # Normalization (0 to 1)
  Min_Val = np.zeros(Dim)
  Max_Val = np.zeros(Dim)

  for i in range(Dim):
      Min_Val[i] = np.min(Data[:,i])
      Data[:,i] = Data[:,i] - np.min(Data[:,i])
      Max_Val[i] = np.max(Data[:,i])
      Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)

  # %% Missing introducing
  # p_miss_vec = p_miss * np.ones((Dim,1))

  Missing = np.array(dfm.notnull().astype(int))

  dfm = np.array(dfm)
  dfm = np.where(np.isnan(dfm), np.ma.array(dfm,
                mask = np.isnan(dfm)).mean(axis = 0), dfm)  #заменяем все пропуски на среднее

  # нормализуем массив с пропусками
  Min_Val = np.zeros(Dim)
  Max_Val = np.zeros(Dim)

  for i in range(Dim):
    Min_Val[i] = np.min(dfm[:,i])
    dfm[:,i] = dfm[:,i] - np.min(dfm[:,i])
    Max_Val[i] = np.max(dfm[:,i])
    dfm[:,i] = dfm[:,i] / (np.max(dfm[:,i]) + 1e-6)

# разделяем на обучающую и тестовую выборки

  idx = np.random.permutation(No)

  Train_No = int(No * train_rate)
  # Test_No = No - Train_No
  Test_No = 255

  # Train / Test Features
  trainX = Data[idx[:Train_No],:]
  # testX = Data[idx[Train_No:],:]
  testX = Data

  # Train / Test Missing Indicators
  trainM = Missing[idx[:Train_No],:]
  # testM = Missing[idx[Train_No:],:]
  testM = Missing


  use_gpu = False
  if use_gpu:
      torch.cuda.set_device(0)

  #%% 1. дискриминатор
  global D_W1, D_W2, D_W3, D_b1, D_b2, D_b3
  if use_gpu is True:
      D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # данные + подсказанные значения
      D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

      D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
      D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

      D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
      D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")       #вывод
  else:
      D_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # данные + подсказанные значения
      D_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

      D_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
      D_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

      D_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
      D_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)       # вывод

  theta_D = [D_W1, D_W2, D_W3, D_b1, D_b2, D_b3]

  #%% 2. генератор
  global G_W1, G_W2, G_W3, G_b1, G_b2, G_b3
  if use_gpu is True:
      G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True, device="cuda")     # данные + маска пропусков
      G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True, device="cuda")

      G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True, device="cuda")
      G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True, device="cuda")

      G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True, device="cuda")
      G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True, device="cuda")
  else:
      G_W1 = torch.tensor(xavier_init([Dim*2, H_Dim1]),requires_grad=True)     # данные + маска пропусков
      G_b1 = torch.tensor(np.zeros(shape = [H_Dim1]),requires_grad=True)

      G_W2 = torch.tensor(xavier_init([H_Dim1, H_Dim2]),requires_grad=True)
      G_b2 = torch.tensor(np.zeros(shape = [H_Dim2]),requires_grad=True)

      G_W3 = torch.tensor(xavier_init([H_Dim2, Dim]),requires_grad=True)
      G_b3 = torch.tensor(np.zeros(shape = [Dim]),requires_grad=True)

  theta_G = [G_W1, G_W2, G_W3, G_b1, G_b2, G_b3]



  optimizer_D = torch.optim.SGD(params=theta_D) # оптимизатор для дискриминатора
  optimizer_G = torch.optim.SGD(params=theta_G)# оптимизатор для генератора

  for it in tqdm(range(5000)):

    #ввод
    mb_idx = sample_idx(Train_No, mb_size)
    X_mb = trainX[mb_idx,:]

    Z_mb = sample_Z(mb_size, Dim)
    M_mb = trainM[mb_idx,:]
    H_mb1 = sample_M(mb_size, Dim, 1-p_hint)
    H_mb = M_mb * H_mb1

    New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb

    if use_gpu is True:
        X_mb = torch.tensor(X_mb, device="cuda")
        M_mb = torch.tensor(M_mb, device="cuda")
        H_mb = torch.tensor(H_mb, device="cuda")
        New_X_mb = torch.tensor(New_X_mb, device="cuda")
    else:
        X_mb = torch.tensor(X_mb)
        M_mb = torch.tensor(M_mb)
        H_mb = torch.tensor(H_mb)
        New_X_mb = torch.tensor(New_X_mb)

    optimizer_D.zero_grad()
    D_loss_curr = discriminator_loss(M=M_mb, New_X=New_X_mb, H=H_mb)
    D_loss_curr.backward()
    optimizer_D.step()

    optimizer_G.zero_grad()
    G_loss_curr, MSE_train_loss_curr, MSE_test_loss_curr = generator_loss(X=X_mb, M=M_mb, New_X=New_X_mb, H=H_mb) # , alpha = alpha
    G_loss_curr.backward()
    optimizer_G.step()



    train_loss.append(float(np.sqrt(MSE_train_loss_curr.item())))
    tst_loss.append(float(np.sqrt(MSE_test_loss_curr.item())))

    #считаем ошибки
    if it % 100 == 0:
        print('Iter: {}'.format(it))
        print('Train_loss: {:.4}'.format(np.sqrt(MSE_train_loss_curr.item())))
        # print('Train_loss: {:.4}'.format(MSE_train_loss_curr.item()))
        print('Test_loss: {:.4}'.format(np.sqrt(MSE_test_loss_curr.item())))
        # print('Test_loss: {:.4}'.format(MSE_test_loss_curr.item()))
        print()



  Z_mb = sample_Z(Test_No, Dim)
  M_mb = testM
  X_mb = testX

  New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

  if use_gpu is True:
      X_mb = torch.tensor(X_mb, device='cuda')
      M_mb = torch.tensor(M_mb, device='cuda')
      New_X_mb = torch.tensor(New_X_mb, device='cuda')
  else:
      X_mb = torch.tensor(X_mb)
      M_mb = torch.tensor(M_mb)
      New_X_mb = torch.tensor(New_X_mb)

  MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)

  # print('Final Test RMSE: ' + str(np.sqrt(MSE_final.item())))
  print('Final Test RMSE: ' + str(MSE_final.item()))

  imputed_data_test = M_mb * X_mb + (1-M_mb) * Sample
  print("Imputed test data:")
  # # np.set_printoptions(formatter={'float': lambda x: "{0:0.8f}".format(x)})

  imputed_data_test = imputed_data_test.detach().numpy()
  Data_denorm_test = np.zeros_like(pd.DataFrame(imputed_data_test, columns = dfm1.columns)) # создаем массив нулей для денормализации

  for i in range(Dim):
    Data_denorm_test[:,i] = imputed_data_test[:,i] * (Max_Val[i] + 1e-6) + Min_Val[i] # денормализуем

  denom_test = pd.DataFrame(Data_denorm_test, columns = dfm1.columns) # превращаем в табличный вид

  # Z_mb = sample_Z(255, Dim)
  # M_mb = Missing
  # X_mb = Data # dfm

  # New_X_mb = M_mb * X_mb + (1-M_mb) * Z_mb  # Missing Data Introduce

  # if use_gpu is True:
  #     X_mb = torch.tensor(X_mb, device='cuda')
  #     M_mb = torch.tensor(M_mb, device='cuda')
  #     New_X_mb = torch.tensor(New_X_mb, device='cuda')
  # else:
  #     X_mb = torch.tensor(X_mb)
  #     M_mb = torch.tensor(M_mb)
  #     New_X_mb = torch.tensor(New_X_mb)

  # MSE_final, Sample = test_loss(X=X_mb, M=M_mb, New_X=New_X_mb)

  # imputed_data = M_mb * X_mb + (1-M_mb) * Sample
  # imputed_data = imputed_data.detach().numpy()

  # Data_denorm = np.zeros_like(pd.DataFrame(imputed_data, columns = dfm1.columns))

  # for i in range(Dim):
  #   Data_denorm[:,i] = imputed_data[:,i] * (Max_Val[i] + 1e-6) + Min_Val[i]
  # denom = pd.DataFrame(Data_denorm, columns = dfm1.columns)





  # denom[int_cols] = sc.inverse_transform(denom[int_cols])

  return denom_test, np.sqrt(MSE_final.item()), train_loss, tst_loss # возвращаем импутированный массив

In [ ]:
dft1

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,8.0,2.0,6.0,3.0,3.0,2.0,3.0,1,4.0,...,4.0,4.0,4.0,2.0,2.0,2.0,2.0,49300.0,3.0,1.0
1,44.0,39.0,3.0,8.0,5.0,6.0,6.0,7.0,2,6.0,...,7.0,7.0,7.0,6.0,8.0,7.0,3.0,219833.0,6.0,1.0
2,29.0,13.0,2.0,6.0,3.0,3.0,3.0,3.0,1,5.0,...,4.0,4.0,5.0,3.0,3.0,3.0,2.0,74772.0,4.0,1.0
3,36.0,25.0,3.0,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,5.0,3.0,130721.0,5.0,1.0
4,28.0,9.0,2.0,6.0,3.0,3.0,3.0,3.0,1,4.0,...,4.0,4.0,4.0,2.0,3.0,2.0,2.0,58085.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,33.0,20.0,3.0,7.0,4.0,4.0,4.0,4.0,1,5.0,...,5.0,5.0,5.0,4.0,4.0,4.0,6.0,107060.0,5.0,1.0
251,36.0,25.0,3.0,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,5.0,3.0,130122.0,5.0,1.0
252,28.0,11.0,2.0,6.0,3.0,3.0,3.0,3.0,1,5.0,...,4.0,4.0,4.0,2.0,3.0,2.0,2.0,65887.0,4.0,1.0
253,36.0,26.0,3.0,7.0,4.0,5.0,5.0,5.0,1,5.0,...,5.0,5.0,6.0,5.0,5.0,5.0,3.0,133560.0,5.0,1.0
254,35.0,24.0,3.0,7.0,4.0,4.0,4.0,5.0,1,5.0,...,5.0,5.0,6.0,4.0,5.0,4.0,3.0,122581.0,5.0,1.0

In [ ]:

Data = np.array(dft1)

# параметры
No = len(Data)
Dim = len(Data[0,:])

# размерность
H_Dim1 = Dim
H_Dim2 = Dim

# нормализация
Min_Val = np.zeros(Dim)
Max_Val = np.zeros(Dim)

for i in range(Dim):
    Min_Val[i] = np.min(Data[:,i])
    Data[:,i] = Data[:,i] - np.min(Data[:,i])
    Max_Val[i] = np.max(Data[:,i])
    Data[:,i] = Data[:,i] / (np.max(Data[:,i]) + 1e-6)


Missing = np.array(dfm.notnull().astype(int))


#обучение и тест
train_rate = 0.75
idx = np.random.permutation(No)
Train_No = int(No * train_rate)
# Test_No = No - Train_No
Test_No = 255

# обучающая и тестова выборки
trainX = Data[idx[:Train_No],:]
# testX = Data[idx[Train_No:],:]
testX = Data

# индикаторы пропусков
trainM = Missing[idx[:Train_No],:]
# testM = Missing[idx[Train_No:],:]
testM = Missing

#%% функции

def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)

# генератор подсказанных значений
def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C

use_gpu = False

In [ ]:
def generator(new_x,m):

    inputs = torch.cat(dim = 1, tensors = [new_x,m])  # маска пропусков + данные
    G_h1 = F.leaky_relu(torch.matmul(inputs, G_W1) + G_b1)
    # G_h1 = F.batch_norm(G_h1)
    G_h1_drop = F.dropout(G_h1, p=0.2, training=True)
    G_h2 = F.relu(torch.matmul(G_h1_drop, G_W2) + G_b2)
    # G_h1 = F.batch_norm(G_h2)
    # G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] normalized Output
    G_prob = torch.sigmoid(torch.matmul(G_h2, G_W3) + G_b3) # [0,1] нормализованный вывод

    return G_prob

#%% 2. Discriminator
def discriminator(new_x, h):

    inputs = torch.cat(dim = 1, tensors = [new_x,h])  # подсказанные значения + данные
    D_h1 = F.relu(torch.matmul(inputs, D_W1) + D_b1)
    D_h1_drop = F.dropout(D_h1, p=0.6, training=True)

    D_h2 = F.relu(torch.matmul(D_h1, D_W2) + D_b2)
    D_logit = torch.matmul(D_h2, D_W3) + D_b3
    D_prob = torch.sigmoid(D_logit)  # [0,1] вероятность - является ли значение реальным

    return D_prob

#%% функции
# генерация выборки из Z
def sample_Z(m, n):
    return np.random.uniform(0., 0.01, size = [m, n])

# генерация мини-батча
def sample_idx(m, n):
    A = np.random.permutation(m)
    idx = A[:n]
    return idx


def discriminator_loss(M, New_X, H):
    # генератор
    G_sample = generator(New_X,M)
    # совмещаем с исходными данными
    Hat_New_X = New_X * M + G_sample * (1-M)

    # дискриминатор
    D_prob = discriminator(Hat_New_X, H)

    # ошибка (функционал)
    D_loss = -torch.mean(M * torch.log(D_prob + 1e-8) + (1-M) * torch.log(1. - D_prob + 1e-8), dtype=torch.float32)
    return D_loss

def generator_loss(X, M, New_X, H):

    # генератор

    G_sample = generator(New_X,M)

    # овмещаем с исходными данными
    Hat_New_X = New_X * M + G_sample * (1-M)

    # дискриминатор
    D_prob = discriminator(Hat_New_X, H)

    #%% Loss
    G_loss1 = -torch.mean((1-M) * torch.log(D_prob + 1e-8), dtype=torch.float32) # ошибка (без ошибки обучения)

    # ошибка (MSE - для интервальных)
    MSE_train_loss1 = torch.mean((M * New_X - M * G_sample)**2, dtype=torch.float32) / torch.mean(M, dtype=torch.float32)
    # # ошибка (accuracy - для категориальных)
    # t = ((M) * X)
    # p = ((M)*G_sample)
    # MSE_train_loss = ((((t-p).abs() <= 0.3) * (M)).sum() /  (M).sum())

    # ошибка (функционал для категориальных)
    # G_loss = G_loss1 + alpha*0.2 * (1/MSE_train_loss) + alpha*0.8 * MSE_train_loss1

    # ошибка (функционал для интервальных)
    G_loss = G_loss1 + alpha* MSE_train_loss1
    # alpha = alpha*0.9

    #%% ТЕСТОВАЯ ОШИБКА
    # для интервальных
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2, dtype=torch.float32) / torch.mean(1-M, dtype=torch.float32)

    # для категориальных
    # t = ((1-M) * X)
    # p = ((1-M)*G_sample)
    # MSE_test_loss = ((((t-p).abs() <= 0.3) * (1-M)).sum() /  (1-M).sum())

    return G_loss, MSE_train_loss1, MSE_test_loss

def test_loss(X, M, New_X):

    # генератор
    G_sample = generator(New_X,M)

    #%% MSE для интервальных
    MSE_test_loss = torch.mean(((1-M) * X - (1-M)*G_sample)**2, dtype=torch.float32) / torch.mean(1-M, dtype=torch.float32)
    #%% accuracy для категориальных
    # t = ((1-M) * X)
    # p = ((1-M) * G_sample)

    #%% общая ошибкаи для категориальных
    # MSE_test_loss = ((((t-p).abs() <= 0.3) * (1-M)).sum() /  (1-M).sum())

    return MSE_test_loss, G_sample

def xavier_init(size):
    in_dim = size[0]
    xavier_stddev = 1. / np.sqrt(in_dim / 2.)
    return np.random.normal(size = size, scale = xavier_stddev)


def sample_M(m, n, p):
    A = np.random.uniform(0., 1., size = [m, n])
    B = A > p
    C = 1.*B
    return C

In [ ]:
def round_(x):
    return np.where(x % 1 >= 0.5, np.ceil(x), np.floor(x))

In [ ]:
import time

In [ ]:
start_time = time.time()
mb_size = 128
p_hint = 0.8
alpha = 2000
train_rate = 0.8

start_time = time.time()

d = GAIN(dft1, dfm1, int_cols, mb_size, p_hint, alpha, train_rate)
print("--- %s seconds ---" % (time.time() - start_time))

  1%|          | 11/1000 [00:00<00:09, 105.32it/s]

Iter: 0
Train_loss: 0.4433
Test_loss: 0.507

 12%|█▏        | 119/1000 [00:00<00:06, 126.18it/s]

Iter: 100
Train_loss: 0.136
Test_loss: 0.2267

 22%|██▎       | 225/1000 [00:01<00:06, 123.94it/s]

Iter: 200
Train_loss: 0.1166
Test_loss: 0.1886

 33%|███▎      | 326/1000 [00:02<00:05, 120.24it/s]

Iter: 300
Train_loss: 0.1117
Test_loss: 0.1852

 41%|████▏     | 414/1000 [00:03<00:04, 118.18it/s]

Iter: 400
Train_loss: 0.1001
Test_loss: 0.1701

 52%|█████▏    | 518/1000 [00:04<00:04, 119.01it/s]

Iter: 500
Train_loss: 0.09543
Test_loss: 0.1838

 62%|██████▏   | 623/1000 [00:05<00:03, 121.97it/s]

Iter: 600
Train_loss: 0.09469
Test_loss: 0.1537

 71%|███████▏  | 714/1000 [00:05<00:02, 120.29it/s]

Iter: 700
Train_loss: 0.0888
Test_loss: 0.173

 82%|████████▏ | 821/1000 [00:06<00:01, 131.96it/s]

Iter: 800
Train_loss: 0.08713
Test_loss: 0.1637

 92%|█████████▏| 917/1000 [00:07<00:00, 130.57it/s]

Iter: 900
Train_loss: 0.08638
Test_loss: 0.167

100%|██████████| 1000/1000 [00:08<00:00, 121.38it/s]

Final Test RMSE: 0.042593494057655334
Imputed test data:
--- 8.26034164428711 seconds ---

# Реализация GAIN

In [ ]:
# def round_(x):
#   if (x % 1) >= 0.5:
#     return(np.ceil(x))
#   else:
    # return(np.floor(x))

def round_(x):
    return np.where(x % 1 >= 0.5, np.ceil(x), np.floor(x))

In [ ]:
c = ['%', 'agea', 'agewrk', 'change_sal', 'edu', 'fctr_succ1', 'fctr_succ2',
       'fctr_succ3', 'fctr_succ4', 'gndr', 'impmot1', 'impmot2', 'impmot3',
       'impmot4', 'impmot5', 'impmot6', 'impmot7', 'impmot8', 'impmot9',
       'incm', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'marital_stat', 'money_what_employer', 'money_what_free_other',
       'money_what_persona', 'mot1', 'mot10', 'mot11', 'mot12', 'mot13',
       'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6', 'mot7', 'mot8', 'mot9',
       'num_crs', 'plcwrk', 'profwrk', 'sal', 'sat_wrk', 'title_wrk'] #'rmse_tot', 'rmse_tot_mcar', 'rmse_tot_mar'

df = pd.DataFrame(columns = c)
df_total = pd.DataFrame(columns = c)
# df_stat_total = pd.DataFrame()
df_vars = pd.DataFrame(columns = c)
# df_vars_full = pd.DataFrame()
sp = []

for i in range(1, 2):
  print('Доля пропусков', i)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar_.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(data_mis.shape[0]):
    sp = [i/10]
    sp1 = [i/10]
    # df.loc[ind, '%'] = i/10

    df_total.loc[ind, '%'] =  i/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    dfm = pd.concat([dfm1[int_cols], dft1[cat_ord]], axis=1)
    # dfm = pd.concat([dfm1[cat_ord], dft1[int_cols]], axis=1)
    dfm = dfm[sorted(dft1.columns)]

    Missing = np.array(dfm.notnull().astype(int))
    Missing_data = dfm.notnull().astype(int)


    imp_data, mse_test, train, test = GAIN(dft1, dfm1, int_cols, mb_size, p_hint, alpha, train_rate) # импутация данных
    # sp.append(imp_data)

    # часть кода для категориальных данных

    # imp_data[cat_ord] = round_(imp_data[cat_ord])
    # for catv in mis_cat_ord:
    #   p = imp_data[catv]
    #   t = dft1[catv]
    #   m = dfm[catv]

    #   f = f1(t[m.isna()==1], p[m.isna()==1], average='macro')
    #   ac = acc(t[m.isna()==1], p[m.isna()==1])
    #   df.loc[ind, catv+'_f1'] = f
    #   df.loc[ind, catv+'_acc'] = ac
    #   df_vars.loc[ind, catv] = p.var()

    # расчет ошибок и запись в таблицы
    rmse_part = np.sqrt(((dft1 - imp_data)**2).sum() / np.ceil(i/10 * 255))
    sp.extend(rmse_part.to_list())
    sp1.extend(imp_data.var().to_list())

    df.loc[len(df)] = sp
    df_vars.loc[len(df_vars)] = sp1




    rmse_tot = rmse(np.array(dft1)[1-Missing == 1], np.array(imp_data)[1-Missing == 1])
    df_total.loc[ind, 'rmse_tot'] =  rmse_tot
    rmse_tot_mcar = rmse(np.array(dft1[mcar_int])[1-Missing_data[mcar_int] == 1], np.array(imp_data[mcar_int])[1-Missing_data[mcar_int] == 1])
    df_total.loc[ind, 'rmse_tot_mcar'] =  rmse_tot_mcar
    rmse_tot_mar = rmse(np.array(dft1[mar_int])[(1-Missing_data[mar_int]) == 1], np.array(imp_data[mar_int])[1-Missing_data[mar_int] == 1])
    df_total.loc[ind, 'rmse_tot_mar'] =  rmse_tot_mar
    df_total.loc[ind, 'mse_test'] =  mse_test


    df_total.loc[ind, 'train'] = '1'
    df_total.at[ind, 'train'] =  train
    df_total.loc[ind, 'test'] = '1'
    df_total.at[ind, 'test'] =  test

    # df = pd.concat([df, pd.DataFrame(rmse_part).transpose()])


    print(df.shape)
    print(df_total.shape)
    print(df_vars.shape)

Доля пропусков 1
--------------------------------------

  0%|          | 10/5000 [00:00<05:16, 15.74it/s]

Iter: 0
Train_loss: 0.4157
Test_loss: 0.4189

  2%|▏         | 110/5000 [00:02<01:04, 75.42it/s]

Iter: 100
Train_loss: 0.1441
Test_loss: 0.2033

  4%|▍         | 216/5000 [00:03<01:00, 78.71it/s]

Iter: 200
Train_loss: 0.1248
Test_loss: 0.1949

  6%|▌         | 308/5000 [00:04<01:10, 66.20it/s]

Iter: 300
Train_loss: 0.1137
Test_loss: 0.2234

  8%|▊         | 415/5000 [00:05<00:43, 105.69it/s]

Iter: 400
Train_loss: 0.1037
Test_loss: 0.1972

 10%|█         | 525/5000 [00:06<00:38, 117.24it/s]

Iter: 500
Train_loss: 0.09967
Test_loss: 0.2064

 12%|█▏        | 616/5000 [00:07<00:34, 125.66it/s]

Iter: 600
Train_loss: 0.09311
Test_loss: 0.1795

 14%|█▍        | 717/5000 [00:08<00:35, 121.82it/s]

Iter: 700
Train_loss: 0.09377
Test_loss: 0.2082

 16%|█▋        | 821/5000 [00:09<00:32, 127.02it/s]

Iter: 800
Train_loss: 0.09156
Test_loss: 0.2053

 18%|█▊        | 916/5000 [00:10<00:33, 122.42it/s]

Iter: 900
Train_loss: 0.08687
Test_loss: 0.1942

 20%|██        | 1020/5000 [00:11<00:34, 115.07it/s]

Iter: 1000
Train_loss: 0.08332
Test_loss: 0.183

 22%|██▏       | 1114/5000 [00:11<00:30, 128.52it/s]

Iter: 1100
Train_loss: 0.07825
Test_loss: 0.182

 24%|██▍       | 1217/5000 [00:12<00:30, 125.30it/s]

Iter: 1200
Train_loss: 0.08244
Test_loss: 0.1852

 26%|██▋       | 1321/5000 [00:13<00:29, 126.17it/s]

Iter: 1300
Train_loss: 0.07685
Test_loss: 0.1473

 28%|██▊       | 1416/5000 [00:14<00:28, 124.49it/s]

Iter: 1400
Train_loss: 0.07772
Test_loss: 0.1844

 30%|███       | 1512/5000 [00:14<00:28, 122.81it/s]

Iter: 1500
Train_loss: 0.0783
Test_loss: 0.1987

 32%|███▏      | 1611/5000 [00:16<00:38, 87.16it/s]

Iter: 1600
Train_loss: 0.07554
Test_loss: 0.1593

 34%|███▍      | 1720/5000 [00:17<00:37, 88.02it/s]

Iter: 1700
Train_loss: 0.07237
Test_loss: 0.1498

 36%|███▌      | 1808/5000 [00:18<00:39, 80.23it/s]

Iter: 1800
Train_loss: 0.07424
Test_loss: 0.186

 38%|███▊      | 1924/5000 [00:19<00:30, 102.12it/s]

Iter: 1900
Train_loss: 0.07082
Test_loss: 0.172

 40%|████      | 2012/5000 [00:20<00:25, 116.91it/s]

Iter: 2000
Train_loss: 0.07177
Test_loss: 0.1793

 42%|████▏     | 2118/5000 [00:21<00:23, 123.24it/s]

Iter: 2100
Train_loss: 0.07123
Test_loss: 0.1763

 45%|████▍     | 2227/5000 [00:22<00:21, 127.53it/s]

Iter: 2200
Train_loss: 0.06665
Test_loss: 0.1586

 46%|████▋     | 2322/5000 [00:22<00:21, 125.53it/s]

Iter: 2300
Train_loss: 0.06694
Test_loss: 0.229

 48%|████▊     | 2415/5000 [00:23<00:22, 117.29it/s]

Iter: 2400
Train_loss: 0.068
Test_loss: 0.1611

 50%|█████     | 2515/5000 [00:24<00:20, 120.90it/s]

Iter: 2500
Train_loss: 0.06576
Test_loss: 0.1946

 52%|█████▏    | 2618/5000 [00:25<00:19, 121.70it/s]

Iter: 2600
Train_loss: 0.06914
Test_loss: 0.1917

 54%|█████▍    | 2722/5000 [00:26<00:18, 121.65it/s]

Iter: 2700
Train_loss: 0.06527
Test_loss: 0.1935

 56%|█████▋    | 2814/5000 [00:26<00:18, 121.08it/s]

Iter: 2800
Train_loss: 0.06479
Test_loss: 0.2128

 58%|█████▊    | 2925/5000 [00:27<00:16, 127.27it/s]

Iter: 2900
Train_loss: 0.06347
Test_loss: 0.2027

 60%|██████    | 3021/5000 [00:28<00:15, 128.92it/s]

Iter: 3000
Train_loss: 0.06255
Test_loss: 0.1689

 62%|██████▏   | 3117/5000 [00:29<00:14, 129.66it/s]

Iter: 3100
Train_loss: 0.06458
Test_loss: 0.1683

 64%|██████▍   | 3212/5000 [00:30<00:19, 92.55it/s]

Iter: 3200
Train_loss: 0.06374
Test_loss: 0.1982

 66%|██████▋   | 3318/5000 [00:31<00:18, 88.77it/s]

Iter: 3300
Train_loss: 0.06432
Test_loss: 0.1946

 68%|██████▊   | 3414/5000 [00:32<00:17, 88.13it/s]

Iter: 3400
Train_loss: 0.06299
Test_loss: 0.2024

 70%|███████   | 3517/5000 [00:33<00:16, 91.84it/s]

Iter: 3500
Train_loss: 0.06312
Test_loss: 0.1784

 72%|███████▏  | 3619/5000 [00:34<00:11, 116.08it/s]

Iter: 3600
Train_loss: 0.06386
Test_loss: 0.1933

 74%|███████▍  | 3721/5000 [00:35<00:10, 125.40it/s]

Iter: 3700
Train_loss: 0.0599
Test_loss: 0.1434

 76%|███████▋  | 3814/5000 [00:36<00:09, 122.93it/s]

Iter: 3800
Train_loss: 0.06098
Test_loss: 0.1761

 78%|███████▊  | 3921/5000 [00:37<00:08, 127.23it/s]

Iter: 3900
Train_loss: 0.06201
Test_loss: 0.1695

 80%|████████  | 4020/5000 [00:38<00:07, 130.79it/s]

Iter: 4000
Train_loss: 0.06142
Test_loss: 0.1419

 82%|████████▏ | 4115/5000 [00:38<00:06, 126.62it/s]

Iter: 4100
Train_loss: 0.06307
Test_loss: 0.1504

 84%|████████▍ | 4220/5000 [00:39<00:06, 125.85it/s]

Iter: 4200
Train_loss: 0.06429
Test_loss: 0.1943

 87%|████████▋ | 4326/5000 [00:40<00:05, 128.01it/s]

Iter: 4300
Train_loss: 0.05846
Test_loss: 0.1773

 88%|████████▊ | 4418/5000 [00:41<00:04, 119.90it/s]

Iter: 4400
Train_loss: 0.05868
Test_loss: 0.1841

 90%|█████████ | 4524/5000 [00:42<00:03, 127.18it/s]

Iter: 4500
Train_loss: 0.05981
Test_loss: 0.1618

 92%|█████████▏| 4615/5000 [00:42<00:03, 122.24it/s]

Iter: 4600
Train_loss: 0.05774
Test_loss: 0.124

 94%|█████████▍| 4720/5000 [00:43<00:02, 122.80it/s]

Iter: 4700
Train_loss: 0.05757
Test_loss: 0.1741

 96%|█████████▋| 4817/5000 [00:44<00:02, 90.60it/s]

Iter: 4800
Train_loss: 0.05923
Test_loss: 0.1588

 98%|█████████▊| 4916/5000 [00:45<00:00, 89.11it/s]

Iter: 4900
Train_loss: 0.05563
Test_loss: 0.2204

100%|██████████| 5000/5000 [00:46<00:00, 106.83it/s]

Final Test RMSE: 0.02848169207572937
Imputed test data:
(1, 47)
(1, 53)
(1, 47)

  0%|          | 7/5000 [00:00<01:12, 68.92it/s]

Iter: 0
Train_loss: 0.4189
Test_loss: 0.3359

  2%|▏         | 123/5000 [00:01<00:44, 109.62it/s]

Iter: 100
Train_loss: 0.1355
Test_loss: 0.1937

  4%|▍         | 221/5000 [00:02<00:37, 125.89it/s]

Iter: 200
Train_loss: 0.1288
Test_loss: 0.1791

  6%|▋         | 316/5000 [00:02<00:35, 130.62it/s]

Iter: 300
Train_loss: 0.1132
Test_loss: 0.1711

  8%|▊         | 425/5000 [00:03<00:35, 128.37it/s]

Iter: 400
Train_loss: 0.1023
Test_loss: 0.1513

 10%|█         | 518/5000 [00:04<00:35, 125.19it/s]

Iter: 500
Train_loss: 0.1022
Test_loss: 0.1721

 12%|█▎        | 625/5000 [00:05<00:35, 124.98it/s]

Iter: 600
Train_loss: 0.09697
Test_loss: 0.1733

 14%|█▍        | 721/5000 [00:06<00:33, 129.14it/s]

Iter: 700
Train_loss: 0.09264
Test_loss: 0.1639

 16%|█▋        | 814/5000 [00:06<00:33, 125.77it/s]

Iter: 800
Train_loss: 0.08564
Test_loss: 0.1721

 18%|█▊        | 919/5000 [00:07<00:33, 121.10it/s]

Iter: 900
Train_loss: 0.08638
Test_loss: 0.1578

 20%|██        | 1022/5000 [00:08<00:33, 120.29it/s]

Iter: 1000
Train_loss: 0.08317
Test_loss: 0.137

 22%|██▏       | 1118/5000 [00:09<00:29, 129.97it/s]

Iter: 1100
Train_loss: 0.08169
Test_loss: 0.1514

 24%|██▍       | 1225/5000 [00:10<00:30, 125.45it/s]

Iter: 1200
Train_loss: 0.08078
Test_loss: 0.16

 26%|██▋       | 1320/5000 [00:10<00:28, 129.78it/s]

Iter: 1300
Train_loss: 0.08033
Test_loss: 0.1513

 28%|██▊       | 1410/5000 [00:11<00:39, 90.97it/s]

Iter: 1400
Train_loss: 0.07639
Test_loss: 0.1372

 30%|███       | 1511/5000 [00:12<00:35, 97.99it/s]

Iter: 1500
Train_loss: 0.07477
Test_loss: 0.1473

 32%|███▏      | 1613/5000 [00:14<00:37, 90.54it/s]

Iter: 1600
Train_loss: 0.07394
Test_loss: 0.1714

 34%|███▍      | 1710/5000 [00:15<00:42, 77.82it/s]

Iter: 1700
Train_loss: 0.06792
Test_loss: 0.162

 36%|███▋      | 1818/5000 [00:16<00:25, 122.51it/s]

Iter: 1800
Train_loss: 0.07183
Test_loss: 0.1454

 38%|███▊      | 1916/5000 [00:16<00:22, 135.04it/s]

Iter: 1900
Train_loss: 0.06997
Test_loss: 0.1481

 40%|████      | 2015/5000 [00:17<00:22, 130.05it/s]

Iter: 2000
Train_loss: 0.06706
Test_loss: 0.137

 42%|████▏     | 2124/5000 [00:18<00:22, 126.38it/s]

Iter: 2100
Train_loss: 0.06862
Test_loss: 0.1438

 44%|████▍     | 2219/5000 [00:19<00:22, 123.67it/s]

Iter: 2200
Train_loss: 0.06584
Test_loss: 0.1305

 46%|████▋     | 2317/5000 [00:19<00:19, 134.84it/s]

Iter: 2300
Train_loss: 0.06834
Test_loss: 0.1417

 49%|████▊     | 2427/5000 [00:20<00:19, 134.91it/s]

Iter: 2400
Train_loss: 0.06346
Test_loss: 0.1262

 50%|█████     | 2523/5000 [00:21<00:19, 128.53it/s]

Iter: 2500
Train_loss: 0.06503
Test_loss: 0.134

 52%|█████▏    | 2615/5000 [00:22<00:20, 115.68it/s]

Iter: 2600
Train_loss: 0.06493
Test_loss: 0.1735

 55%|█████▍    | 2726/5000 [00:23<00:17, 127.76it/s]

Iter: 2700
Train_loss: 0.06755
Test_loss: 0.1281

 56%|█████▋    | 2824/5000 [00:23<00:17, 126.75it/s]

Iter: 2800
Train_loss: 0.0634
Test_loss: 0.1446

 59%|█████▊    | 2926/5000 [00:24<00:17, 119.04it/s]

Iter: 2900
Train_loss: 0.06269
Test_loss: 0.1347

 60%|██████    | 3014/5000 [00:25<00:19, 101.74it/s]

Iter: 3000
Train_loss: 0.06202
Test_loss: 0.1549

 62%|██████▏   | 3117/5000 [00:26<00:19, 96.00it/s]

Iter: 3100
Train_loss: 0.05872
Test_loss: 0.1563

 64%|██████▍   | 3216/5000 [00:27<00:20, 87.38it/s]

Iter: 3200
Train_loss: 0.06042
Test_loss: 0.1368

 66%|██████▋   | 3313/5000 [00:29<00:22, 76.39it/s]

Iter: 3300
Train_loss: 0.06295
Test_loss: 0.1421

 68%|██████▊   | 3425/5000 [00:30<00:13, 120.12it/s]

Iter: 3400
Train_loss: 0.05776
Test_loss: 0.1226

 70%|███████   | 3522/5000 [00:30<00:11, 127.15it/s]

Iter: 3500
Train_loss: 0.05728
Test_loss: 0.1243

 72%|███████▏  | 3615/5000 [00:31<00:10, 128.67it/s]

Iter: 3600
Train_loss: 0.06351
Test_loss: 0.1474

 74%|███████▍  | 3721/5000 [00:32<00:10, 121.96it/s]

Iter: 3700
Train_loss: 0.06048
Test_loss: 0.1167

 76%|███████▋  | 3813/5000 [00:33<00:10, 115.12it/s]

Iter: 3800
Train_loss: 0.05864
Test_loss: 0.1235

 78%|███████▊  | 3925/5000 [00:34<00:09, 118.97it/s]

Iter: 3900
Train_loss: 0.05995
Test_loss: 0.1538

 80%|████████  | 4023/5000 [00:34<00:07, 128.49it/s]

Iter: 4000
Train_loss: 0.06109
Test_loss: 0.1172

 82%|████████▏ | 4116/5000 [00:35<00:07, 125.09it/s]

Iter: 4100
Train_loss: 0.05766
Test_loss: 0.1579

 85%|████████▍ | 4227/5000 [00:36<00:05, 130.20it/s]

Iter: 4200
Train_loss: 0.06037
Test_loss: 0.1339

 86%|████████▋ | 4319/5000 [00:37<00:05, 113.51it/s]

Iter: 4300
Train_loss: 0.05721
Test_loss: 0.1295

 88%|████████▊ | 4422/5000 [00:38<00:05, 114.97it/s]

Iter: 4400
Train_loss: 0.0595
Test_loss: 0.1316

 90%|█████████ | 4521/5000 [00:39<00:04, 115.13it/s]

Iter: 4500
Train_loss: 0.05575
Test_loss: 0.1362

 92%|█████████▏| 4610/5000 [00:39<00:03, 98.32it/s]

Iter: 4600
Train_loss: 0.05922
Test_loss: 0.1041

 94%|█████████▍| 4712/5000 [00:41<00:03, 91.60it/s]

Iter: 4700
Train_loss: 0.0572
Test_loss: 0.1111

 96%|█████████▋| 4820/5000 [00:42<00:01, 94.33it/s]

Iter: 4800
Train_loss: 0.05589
Test_loss: 0.107

 98%|█████████▊| 4913/5000 [00:43<00:01, 81.07it/s]

Iter: 4900
Train_loss: 0.05658
Test_loss: 0.1236

100%|██████████| 5000/5000 [00:44<00:00, 112.92it/s]

Final Test RMSE: 0.019673211500048637
Imputed test data:
(2, 47)
(2, 53)
(2, 47)

  0%|          | 13/5000 [00:00<00:38, 128.28it/s]

Iter: 0
Train_loss: 0.4568
Test_loss: 0.5214

  2%|▏         | 117/5000 [00:00<00:38, 125.35it/s]

Iter: 100
Train_loss: 0.1399
Test_loss: 0.1561

  4%|▍         | 222/5000 [00:01<00:39, 119.94it/s]

Iter: 200
Train_loss: 0.1217
Test_loss: 0.1647

  6%|▋         | 314/5000 [00:02<00:39, 117.83it/s]

Iter: 300
Train_loss: 0.1168
Test_loss: 0.1453

  8%|▊         | 414/5000 [00:03<00:39, 116.96it/s]

Iter: 400
Train_loss: 0.1055
Test_loss: 0.1407

 10%|█         | 520/5000 [00:04<00:35, 124.90it/s]

Iter: 500
Train_loss: 0.1049
Test_loss: 0.1425

 12%|█▎        | 625/5000 [00:05<00:33, 130.18it/s]

Iter: 600
Train_loss: 0.09533
Test_loss: 0.1398

 14%|█▍        | 722/5000 [00:05<00:33, 126.41it/s]

Iter: 700
Train_loss: 0.08783
Test_loss: 0.1237

 16%|█▋        | 818/5000 [00:06<00:33, 123.59it/s]

Iter: 800
Train_loss: 0.08559
Test_loss: 0.09472

 18%|█▊        | 923/5000 [00:07<00:32, 127.11it/s]

Iter: 900
Train_loss: 0.08566
Test_loss: 0.1262

 20%|██        | 1017/5000 [00:08<00:30, 129.25it/s]

Iter: 1000
Train_loss: 0.07692
Test_loss: 0.1089

 22%|██▏       | 1123/5000 [00:09<00:31, 125.00it/s]

Iter: 1100
Train_loss: 0.07966
Test_loss: 0.126

 24%|██▎       | 1175/5000 [00:09<00:31, 123.21it/s]

KeyboardInterrupt:

In [ ]:
len(sp)

47

In [ ]:
from google.colab import files

In [ ]:
df.to_excel('gain_stat_part1_часть1.xlsx')
df_total.to_excel('gain_stat_total1_часть1.xlsx')
df_vars.to_excel('gain_stat_var1_часть1.xlsx')


files.download('gain_stat_part1_часть1.xlsx')
files.download('gain_stat_total1_часть1.xlsx')
files.download('gain_stat_var1_часть1.xlsx')