In [ ]:
import sklearn

In [ ]:
import pandas as pd
import numpy as np
import json
from sklearn.impute import SimpleImputer
from sklearn.metrics import root_mean_squared_error as rmse, f1_score as f1, accuracy_score as acc, precision_score as pr, recall_score as rc
import math
import scipy
from scipy.stats import entropy

In [ ]:
import warnings

def fxn():
    warnings.warn("deprecated", DeprecationWarning)

with warnings.catch_warnings():
    warnings.simplefilter("ignore")
    fxn()

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
for i in range(5, 6):
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar.json'

In [ ]:
data_mis = pd.read_json(file_mis)
data_tar =  pd.read_json(file_tar)

dfm1 = pd.DataFrame(data_mis.loc[0].to_dict())
dft1 = pd.DataFrame(data_tar.loc[0].to_dict())

dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

In [ ]:
cat_cols = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk']

ord_cols = ['edu', 'change_sal',
       'title_wrk', 'incm']

cat_ord = ['gndr', 'marital_stat', 'initiative1_employer',
       'initiative2_persona', 'money_what_employer', 'money_what_persona',
       'money_what_free_other', 'is_spec_crs', 'profwrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_ord = ['agea', 'agewrk', 'fctr_succ1', 'fctr_succ2', 'fctr_succ3',
       'fctr_succ4', 'impmot1', 'impmot2', 'impmot3', 'impmot4', 'impmot5',
       'impmot6', 'impmot7', 'impmot8', 'impmot9', 'mot1', 'mot10', 'mot11',
       'mot12', 'mot13', 'mot14', 'mot2', 'mot3', 'mot4', 'mot5', 'mot6',
       'mot7', 'mot8', 'mot9', 'num_crs', 'plcwrk', 'sal', 'sat_wrk', 'edu', 'change_sal',
       'title_wrk', 'incm']

int_cols = dfm1.drop(cat_cols, axis=1).drop(ord_cols, axis=1).columns


miss_vars= ["marital_stat", "num_crs",
            "mot1", "mot2", "mot3", "mot4", "mot5", "mot6", "mot7", "mot8", "mot9", "mot10", "mot11", "mot12", "mot13", "mot14",
            "edu", "agewrk", "plcwrk", "profwrk", "change_sal", "title_wrk", "sal", "sat_wrk",
            "fctr_succ1", "fctr_succ2", "fctr_succ3", "fctr_succ4",
            "impmot1", "impmot2", "impmot3", "impmot4", "impmot5", "impmot6", "impmot7", "impmot8", "impmot9",
            "agea", "incm"]


mcar = ["marital_stat", "num_crs",
        "mot2", "mot6", "mot9", "mot10", "mot11", "mot12", "mot13",
        "agewrk", "plcwrk", "sat_wrk",
        "fctr_succ3", "fctr_succ4",
        "impmot1", "impmot4", "impmot5", "impmot8", "agea", "incm", "title_wrk"]

mar = ["mot1", "mot3", "mot4", "mot5", "mot7", "mot8", "mot14",
       "edu", "profwrk", "change_sal", "sal", "fctr_succ1",
       "fctr_succ2", "impmot2", "impmot3", "impmot6", "impmot7", "impmot9"]


mcar_cat = ['marital_stat']
mcar_ord = ['incm', 'title_wrk']
mcar_int = ['mot2', 'agea', 'mot9', 'fctr_succ4',
            'mot6', 'mot10', 'mot11', 'mot12', 'mot13',
            'impmot1', 'incm', 'impmot4', 'impmot8', 'fctr_succ3', 'agewrk',
            'plcwrk', 'sat_wrk', 'impmot5', 'num_crs']



mar_int = ['impmot2', 'impmot7', 'mot1', 'mot14', 'impmot6', 'mot7', 'mot3', 'fctr_succ2', 'impmot3', 'mot8', 'mot4', 'impmot9', 'mot5', 'sal', 'fctr_succ1']
mar_cat = ['profwrk']
mar_ord = ['edu', 'change_sal']


not_mis = ['gndr', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'money_what_employer', 'money_what_free_other', 'money_what_persona']


mar_int = ['impmot2', 'impmot7', 'mot1', 'mot14', 'impmot6', 'mot3', 'fctr_succ2', 'impmot3', 'mot8', 'mot4', 'impmot9', 'mot5', 'sal', 'fctr_succ1']
mar_cat = ['profwrk']
mar_ord = ['edu', 'change_sal', 'title_wrk']


not_mis = ['gndr', 'initiative1_employer', 'initiative2_persona', 'is_spec_crs',
       'money_what_employer', 'money_what_free_other', 'money_what_persona']

# hot_deck

In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd


df = pd.DataFrame(dfm1)
def hot_deck(df):
  # Initialize KNNImputer
  imputer = KNNImputer(n_neighbors=1)

  # Impute missing values
  imputed_data = imputer.fit_transform(df)

  # Convert back to DataFrame
  imputed_df = pd.DataFrame(imputed_data, columns=df.columns)
  return imputed_df
# imputed_df.isna().sum().sum()

In [ ]:
df = pd.DataFrame()
df_total = pd.DataFrame()
df_stat = pd.DataFrame()
df_stat_total = pd.DataFrame()
df_vars = pd.DataFrame()
df_vars_full = pd.DataFrame()

import time


for i in range(5, 6):
  print('Доля пропусков', i)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar_.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(data_mis.shape[0]):
    start_time = time.time()
    df.loc[ind, '%'] = i/10

    df_total.loc[ind, '%'] =  i/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    imp_data = hot_deck(dfm1).reset_index(drop = True)
    print("--- %s seconds ---" % (time.time() - start_time))

    for var in dfm1.columns:
    # for var in ['agea']:
      # print('-------------------------', var)
      index_mis = list(map(int, dfm1[var][dfm1[var].isna()].index))
      mis_imput =  imp_data[var].loc[index_mis]
      tar_vals = dft1[var].loc[index_mis]
      if len(tar_vals) == 0:
        df[var] = 'full'
        continue
      else:
        if var in int_cols:
          error = rmse(tar_vals, mis_imput)
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = imp_data[var].var()


        if var in ord_cols:
          mis_imput = mis_imput.apply(lambda row: math.ceil(row))
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

        if var in cat_cols:
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

  # total metrics
    imputed_data = hot_deck(dfm1).reset_index(drop = True)
    im_int = imputed_data[list(set(miss_vars) & set(int_cols))]
    im_ord = imputed_data[list(set(miss_vars) & set(ord_cols))].apply(np.ceil)
    im_cat = imputed_data[list(set(miss_vars) & set(cat_cols))]
    im_cat = imputed_data[list(set(miss_vars) & set(cat_cols))]

    im_cat_mar = imputed_data[mar_cat]
    im_cat_mcar = imputed_data[mcar_cat]

    im_ord_mar = imputed_data[mar_ord]
    im_ord_mcar = imputed_data[mcar_ord]

    im_int_mar = imputed_data[mar_int]
    im_int_mcar = imputed_data[mcar_int]

    imputedvars_int = np.array(im_int)[np.array(dfm1[miss_vars][int_cols].isna())]
    imputedvars_ord = np.array(im_ord)[np.array(dfm1[miss_vars][ord_cols].isna())]
    imputedvars_cat = np.array(im_cat)[np.array(dfm1[list(set(miss_vars) & set(cat_cols))].isna())]

    mar_imputedvars_cat = np.array(im_cat_mar)[np.array(dfm1[mar_cat].isna())]
    mar_imputedvars_ord = np.ceil(np.array(im_ord_mar)[np.array(dfm1[mar_ord].isna())])
    mar_imputedvars_int = np.array(im_int_mar)[np.array(dfm1[mar_int].isna())]
    mcar_imputedvars_cat = np.array(im_cat_mcar)[np.array(dfm1[mcar_cat].isna())]
    mcar_imputedvars_ord = np.ceil(np.array(im_ord_mcar)[np.array(dfm1[mcar_ord].isna())])
    mcar_imputedvars_int = np.array(im_int_mcar)[np.array(dfm1[mcar_int].isna())]


    TargetTagsvars_int = np.array(dft1[miss_vars][int_cols])[dfm1[miss_vars][int_cols].isna()]
    TargetTagsvars_ord = np.array(dft1[miss_vars][ord_cols])[dfm1[miss_vars][ord_cols].isna()]
    TargetTagsvars_cat = np.array(dft1[list(set(miss_vars) & set(cat_cols))])[dfm1[list(set(miss_vars) & set(cat_cols))].isna()]

    mar_TargetTagsvars_cat = np.array(dft1[mar_cat])[dfm1[mar_cat].isna()]
    mar_TargetTagsvars_ord = np.array(dft1[mar_ord])[dfm1[mar_ord].isna()]
    mar_TargetTagsvars_int = np.array(dft1[mar_int])[dfm1[mar_int].isna()]
    mcar_TargetTagsvars_cat = np.array(dft1[mcar_cat])[dfm1[mcar_cat].isna()]
    mcar_TargetTagsvars_ord = np.array(dft1[mcar_ord])[dfm1[mcar_ord].isna()]
    mcar_TargetTagsvars_int = np.array(dft1[mcar_int])[dfm1[mcar_int].isna()]


    df_total.loc[ind, 'total_rmse_int'] = rmse(TargetTagsvars_int, imputedvars_int)

    # df_total.loc[ind, 'total_rmse_ord'] = rmse(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_acc_ord'] = acc(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_f1_ord']  = f1(TargetTagsvars_ord, imputedvars_ord, average ='macro' )
    # df_total['total_pr_ord']  = pr(TargetTagsvars_ord, imputedvars_ord, average ='macro')
    # df_total['total_rc_ord'] = rc(TargetTagsvars_ord, imputedvars_ord, average ='macro')

    df_total.loc[ind, 'total_acc_cat'] = acc(TargetTagsvars_cat, imputedvars_cat)
    df_total.loc[ind, 'total_f1_cat'] = f1(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_pr_cat'] = pr(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_rc_cat'] = rc(TargetTagsvars_cat, imputedvars_cat, average ='macro')

    #mar
    df_total.loc[ind, 'mar_f1_cat']  = f1(mar_TargetTagsvars_cat, mar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mar_f1_ord']  = f1(mar_TargetTagsvars_ord, mar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mar_rmse_int']  = rmse(mar_TargetTagsvars_int, mar_imputedvars_int)
    #mcar
    df_total.loc[ind, 'mcar_f1_cat']  = f1(mcar_TargetTagsvars_cat, mcar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mcar_f1_ord']  = f1(mcar_TargetTagsvars_ord, mcar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mcar_rmse_int']  = rmse(mcar_TargetTagsvars_int, mcar_imputedvars_int)

    if ind%20 == 0:
      print(f'Загружено {ind} из {data_mis.shape[0]}' )

    # if ind == 50: break

    df_stat = pd.concat([df_stat, df])

    df_stat_total = pd.concat([df_stat_total, df_total])
    df_vars_full = pd.concat([df_vars_full, df_vars])

    df_stat = df_stat.drop_duplicates()
    df_stat_total = df_stat_total.drop_duplicates()

    df_vars_full = df_vars_full.drop_duplicates()

  print(df_stat.shape)
  print(df_stat_total.shape)
  print(df_vars_full.shape)

Доля пропусков 5
--------------------------------------
--- 0.08262753486633301 seconds ---
Загружено 0 из 1011
--- 0.06497859954833984 seconds ---
--- 0.06710433959960938 seconds ---
--- 0.06790995597839355 seconds ---
--- 0.09429454803466797 seconds ---
--- 0.06491613388061523 seconds ---
--- 0.0687856674194336 seconds ---
--- 0.06523466110229492 seconds ---

KeyboardInterrupt:

In [ ]:
dfm1

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,NaN,NaN,NaN,3.0,2.0,NaN,NaN,1,NaN,...,4.0,NaN,4.0,2.0,NaN,2.0,2.0,NaN,3.0,NaN
1,43.0,23.0,NaN,NaN,NaN,6.0,6.0,6.0,2,NaN,...,7.0,NaN,NaN,NaN,NaN,7.0,3.0,NaN,6.0,NaN
2,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,1,4.0,...,4.0,NaN,5.0,3.0,NaN,3.0,NaN,237124.0,4.0,NaN
3,35.0,NaN,2.0,7.0,NaN,NaN,4.0,NaN,1,6.0,...,5.0,NaN,NaN,NaN,NaN,5.0,NaN,460455.0,NaN,3.0
4,NaN,6.0,NaN,NaN,3.0,NaN,3.0,3.0,1,NaN,...,NaN,NaN,4.0,NaN,2.0,NaN,2.0,176388.0,3.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,33.0,11.0,2.0,7.0,4.0,3.0,NaN,4.0,1,NaN,...,NaN,NaN,5.0,NaN,4.0,NaN,NaN,367349.0,5.0,NaN
251,35.0,NaN,NaN,7.0,NaN,NaN,4.0,4.0,1,NaN,...,5.0,NaN,NaN,NaN,NaN,NaN,NaN,458208.0,NaN,NaN
252,NaN,6.0,2.0,NaN,NaN,2.0,3.0,3.0,1,4.0,...,4.0,NaN,4.0,NaN,NaN,2.0,2.0,NaN,4.0,NaN
253,36.0,14.0,NaN,7.0,NaN,4.0,NaN,4.0,1,6.0,...,5.0,4.0,6.0,NaN,NaN,NaN,3.0,NaN,5.0,3.0
254,NaN,NaN,2.0,7.0,NaN,NaN,4.0,NaN,1,5.0,...,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

In [ ]:
 hot_deck(dfm1)

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,6.0,2.0,7.0,3.0,2.0,3.0,3.0,1.0,4.0,...,4.0,2.0,4.0,2.0,2.0,2.0,2.0,176388.0,3.0,1.0
1,43.0,23.0,3.0,8.0,6.0,6.0,6.0,6.0,2.0,6.0,...,7.0,6.0,6.0,6.0,8.0,7.0,3.0,731497.0,6.0,3.0
2,30.0,7.0,2.0,7.0,3.0,3.0,3.0,3.0,1.0,4.0,...,4.0,3.0,5.0,3.0,3.0,3.0,2.0,237124.0,4.0,2.0
3,35.0,14.0,2.0,7.0,5.0,4.0,4.0,4.0,1.0,6.0,...,5.0,4.0,6.0,4.0,5.0,5.0,3.0,460455.0,5.0,3.0
4,27.0,6.0,2.0,7.0,3.0,2.0,3.0,3.0,1.0,4.0,...,4.0,2.0,4.0,2.0,2.0,2.0,2.0,176388.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,33.0,11.0,2.0,7.0,4.0,3.0,4.0,4.0,1.0,5.0,...,5.0,3.0,5.0,4.0,4.0,4.0,6.0,367349.0,5.0,2.0
251,35.0,13.0,2.0,7.0,5.0,4.0,4.0,4.0,1.0,5.0,...,5.0,4.0,6.0,4.0,5.0,5.0,3.0,458208.0,5.0,2.0
252,28.0,6.0,2.0,6.0,3.0,2.0,3.0,3.0,1.0,4.0,...,4.0,2.0,4.0,2.0,2.0,2.0,2.0,165876.0,4.0,2.0
253,36.0,14.0,3.0,7.0,4.0,4.0,4.0,4.0,1.0,6.0,...,5.0,4.0,6.0,4.0,5.0,4.0,3.0,475302.0,5.0,3.0
254,34.0,12.0,2.0,7.0,4.0,4.0,4.0,4.0,1.0,5.0,...,5.0,4.0,5.0,4.0,4.0,4.0,6.0,420782.0,5.0,2.0

In [ ]:
dft1

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,5.0,2.0,6.0,3.0,2.0,3.0,3.0,1,4.0,...,4.0,2.0,4.0,2.0,2.0,2.0,2.0,147857.0,3.0,1.0
1,43.0,23.0,3.0,8.0,5.0,6.0,6.0,6.0,2,6.0,...,7.0,6.0,6.0,6.0,7.0,7.0,3.0,702273.0,6.0,3.0
2,30.0,7.0,2.0,6.0,3.0,3.0,3.0,3.0,1,4.0,...,4.0,3.0,5.0,3.0,3.0,3.0,2.0,237124.0,4.0,2.0
3,35.0,14.0,2.0,7.0,4.0,4.0,4.0,4.0,1,6.0,...,5.0,4.0,6.0,4.0,5.0,5.0,3.0,460455.0,5.0,3.0
4,28.0,6.0,2.0,6.0,3.0,2.0,3.0,3.0,1,4.0,...,4.0,2.0,4.0,2.0,2.0,2.0,2.0,176388.0,3.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,33.0,11.0,2.0,7.0,4.0,3.0,4.0,4.0,1,5.0,...,5.0,3.0,5.0,4.0,4.0,4.0,6.0,367349.0,5.0,2.0
251,35.0,14.0,2.0,7.0,4.0,4.0,4.0,4.0,1,5.0,...,5.0,4.0,6.0,4.0,5.0,5.0,3.0,458208.0,5.0,3.0
252,29.0,6.0,2.0,6.0,3.0,2.0,3.0,3.0,1,4.0,...,4.0,2.0,4.0,3.0,3.0,2.0,2.0,203843.0,4.0,2.0
253,36.0,14.0,3.0,7.0,4.0,4.0,4.0,4.0,1,6.0,...,5.0,4.0,6.0,4.0,5.0,5.0,3.0,471012.0,5.0,3.0
254,35.0,13.0,2.0,7.0,4.0,4.0,4.0,4.0,1,5.0,...,5.0,4.0,6.0,4.0,4.0,4.0,3.0,429345.0,5.0,2.0

In [ ]:
mis_imput

4      28.0
5      44.0
8      44.0
9      39.0
11     62.0
       ...
246    35.0
248    35.0
250    33.0
251    35.0
253    36.0
Name: agea, Length: 128, dtype: float64

In [ ]:
rmse(tar_vals, mis_imput)

1.14564392373896

In [ ]:
np.sqrt(((tar_vals-mis_imput)**2).sum() / 128)

np.float64(1.14564392373896)

In [ ]:
((dft1['agea'] - imputed_data['agea'])**2).sum()

np.float64(23327.0)

In [ ]:
imputed_data

,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,impmot1,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,27.0,5.0,2.0,6.0,3.0,3.0,3.0,2.0,1.0,2.0,...,4.0,2.0,2.0,2.0,2.0,2.0,2.0,60664.0,3.0,1.0
1,59.0,23.0,3.0,8.0,6.0,6.0,6.0,6.0,2.0,7.0,...,6.0,6.0,6.0,6.0,8.0,6.0,3.0,232262.0,6.0,3.0
2,35.0,7.0,2.0,7.0,3.0,3.0,3.0,3.0,1.0,3.0,...,5.0,3.0,3.0,3.0,3.0,3.0,2.0,80560.0,4.0,2.0
3,46.0,14.0,3.0,7.0,5.0,5.0,4.0,5.0,1.0,5.0,...,6.0,4.0,4.0,4.0,6.0,4.0,3.0,160810.0,5.0,3.0
4,29.0,6.0,2.0,6.0,3.0,3.0,3.0,3.0,1.0,2.0,...,4.0,2.0,2.0,3.0,3.0,2.0,2.0,68515.0,4.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,39.0,11.0,3.0,7.0,4.0,4.0,4.0,4.0,1.0,4.0,...,5.0,3.0,3.0,4.0,4.0,3.0,6.0,109455.0,5.0,2.0
251,45.0,15.0,3.0,7.0,4.0,4.0,4.0,4.0,1.0,5.0,...,6.0,4.0,4.0,4.0,5.0,4.0,3.0,143155.0,5.0,3.0
252,29.0,6.0,2.0,6.0,3.0,3.0,3.0,2.0,1.0,2.0,...,4.0,2.0,2.0,3.0,3.0,2.0,2.0,73155.0,4.0,2.0
253,46.0,14.0,3.0,7.0,4.0,5.0,4.0,5.0,1.0,5.0,...,6.0,4.0,4.0,4.0,5.0,4.0,3.0,141583.0,5.0,3.0
254,45.0,13.0,3.0,7.0,4.0,4.0,4.0,4.0,1.0,5.0,...,5.0,4.0,4.0,4.0,5.0,4.0,3.0,129824.0,5.0,2.0

In [ ]:
from google.colab import files

In [ ]:
df_stat.to_excel('hot_deck_stat_part2.xlsx')
df_stat_total.to_excel('hot_deck_stat_total2.xlsx')
df_vars_full.to_excel('hot_deck_stat_var2.xlsx')

In [ ]:
files.download('hot_deck_stat_part2.xlsx')
files.download('hot_deck_stat_total2.xlsx')
files.download('hot_deck_stat_var2.xlsx')

# knn

In [ ]:
from sklearn.impute import KNNImputer
import pandas as pd


df = pd.DataFrame(dfm1)
def knn(df, k):
  # Initialize KNNImputer
  imputer = KNNImputer(n_neighbors=k)

  # Impute missing values
  imputed_data = imputer.fit_transform(df)

  # Convert back to DataFrame
  imputed_df = pd.DataFrame(imputed_data, columns=df.columns)
  return imputed_df

a = knn(df, 3)
a.isna().sum().sum()

np.int64(0)

In [ ]:
df = pd.DataFrame()
df_total = pd.DataFrame()
df_stat = pd.DataFrame()
df_stat_total = pd.DataFrame()
df_vars = pd.DataFrame()
df_vars_full = pd.DataFrame()

for i in range(1, 6):
  print('Доля пропусков', i)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(data_mis.shape[0]):
    start_time = time.time()

    df.loc[ind, '%'] = i/10

    df_total.loc[ind, '%'] =  i/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    for k in [2, 3, 5, 7, 9, 11, 13]:
      imp_data = knn(dfm1, k).reset_index(drop = True)
      print("--- %s seconds ---" % (time.time() - start_time))

      for var in dfm1.columns:
        # print('-------------------------', var)
        index_mis = list(map(int, dfm1[var][dfm1[var].isna()].index))
        mis_imput =  imp_data[var].loc[index_mis]
        tar_vals = dft1[var].loc[index_mis]
        if len(tar_vals) == 0:
          df[var] = 'full'
          continue
        else:
          if var in int_cols:
            error = rmse(tar_vals, mis_imput)
            df.loc[ind, var+'_'+str(k)] = error
            # print(var, error)
            df_vars.loc[ind, var] = imp_data[var].var()

          if var in ord_cols:
            mis_imput = mis_imput.apply(lambda row: math.ceil(row))
            error = f1(tar_vals, mis_imput, average ='macro')
            df.loc[ind, var+'_'+str(k)] = error
            # print(var, error)
            df_vars.loc[ind, var] = entropy(imp_data[var])

          if var in cat_cols:
            mis_imput = mis_imput.apply(lambda row: math.ceil(row))
            error = f1(tar_vals, mis_imput, average ='macro')
            df.loc[ind, var+'_'+str(k)] = error
            # print(var, error)
            df_vars.loc[ind, var] = entropy(imp_data[var])

  # total metrics
    for k in [2, 3, 5, 7, 9, 11, 13]:
      imputed_data = knn(dfm1, k).reset_index(drop = True)
      im_int = imputed_data[list(set(miss_vars) & set(int_cols))]
      im_ord = imputed_data[list(set(miss_vars) & set(ord_cols))].apply(np.ceil)
      im_cat = imputed_data[list(set(miss_vars) & set(cat_cols))].apply(np.ceil)


      im_cat_mar = imputed_data[mar_cat]
      im_cat_mcar = imputed_data[mcar_cat]

      im_ord_mar = imputed_data[mar_ord]
      im_ord_mcar = imputed_data[mcar_ord]

      im_int_mar = imputed_data[mar_int]
      im_int_mcar = imputed_data[mcar_int]

      imputedvars_int = np.array(im_int)[np.array(dfm1[miss_vars][int_cols].isna())]
      imputedvars_ord = np.array(im_ord)[np.array(dfm1[miss_vars][ord_cols].isna())]
      imputedvars_cat = np.array(im_cat)[np.array(dfm1[list(set(miss_vars) & set(cat_cols))].isna())]

      mar_imputedvars_cat = np.ceil(np.array(im_cat_mar)[np.array(dfm1[mar_cat].isna())])
      mar_imputedvars_ord = np.ceil(np.array(im_ord_mar)[np.array(dfm1[mar_ord].isna())])
      mar_imputedvars_int = np.array(im_int_mar)[np.array(dfm1[mar_int].isna())]
      mcar_imputedvars_cat = np.ceil(np.array(im_cat_mcar)[np.array(dfm1[mcar_cat].isna())])
      mcar_imputedvars_ord = np.ceil(np.array(im_ord_mcar)[np.array(dfm1[mcar_ord].isna())])
      mcar_imputedvars_int = np.array(im_int_mcar)[np.array(dfm1[mcar_int].isna())]


      TargetTagsvars_int = np.array(dft1[miss_vars][int_cols])[dfm1[miss_vars][int_cols].isna()]
      TargetTagsvars_ord = np.array(dft1[miss_vars][ord_cols])[dfm1[miss_vars][ord_cols].isna()]
      TargetTagsvars_cat = np.array(dft1[list(set(miss_vars) & set(cat_cols))])[dfm1[list(set(miss_vars) & set(cat_cols))].isna()]

      mar_TargetTagsvars_cat = np.ceil(np.array(dft1[mar_cat])[dfm1[mar_cat].isna()])
      mar_TargetTagsvars_ord = np.ceil(np.array(dft1[mar_ord])[dfm1[mar_ord].isna()])
      mar_TargetTagsvars_int = np.array(dft1[mar_int])[dfm1[mar_int].isna()]
      mcar_TargetTagsvars_cat = np.array(dft1[mcar_cat])[dfm1[mcar_cat].isna()]
      mcar_TargetTagsvars_ord = np.array(dft1[mcar_ord])[dfm1[mcar_ord].isna()]
      mcar_TargetTagsvars_int = np.array(dft1[mcar_int])[dfm1[mcar_int].isna()]


      df_total.loc[ind, 'total_rmse_int_'+str(k)] = rmse(TargetTagsvars_int, imputedvars_int)

      # df_total.loc[ind, 'total_rmse_ord'] = rmse(TargetTagsvars_ord, imputedvars_ord )
      df_total.loc[ind, 'total_acc_ord_'+str(k)] = acc(TargetTagsvars_ord, imputedvars_ord )
      df_total.loc[ind, 'total_f1_ord_'+str(k)]  = f1(TargetTagsvars_ord, imputedvars_ord, average ='macro' )
      # df_total['total_pr_ord']  = pr(TargetTagsvars_ord, imputedvars_ord, average ='macro')
      # df_total['total_rc_ord'] = rc(TargetTagsvars_ord, imputedvars_ord, average ='macro')

      df_total.loc[ind, 'total_acc_cat_'+str(k)] = acc(TargetTagsvars_cat, imputedvars_cat)
      df_total.loc[ind, 'total_f1_cat_'+str(k)] = f1(TargetTagsvars_cat, imputedvars_cat, average ='macro')
      # df_total['total_pr_cat'] = pr(TargetTagsvars_cat, imputedvars_cat, average ='macro')
      # df_total['total_rc_cat'] = rc(TargetTagsvars_cat, imputedvars_cat, average ='macro')

      #mar
      df_total.loc[ind, 'mar_f1_cat_'+str(k)]  = f1(mar_TargetTagsvars_cat, mar_imputedvars_cat, average ='macro' )
      df_total.loc[ind, 'mar_f1_ord_'+str(k)]  = f1(mar_TargetTagsvars_ord, mar_imputedvars_ord, average ='macro' )
      df_total.loc[ind, 'mar_rmse_int_'+str(k)]  = rmse(mar_TargetTagsvars_int, mar_imputedvars_int)
      #mcar
      df_total.loc[ind, 'mcar_f1_cat_'+str(k)]  = f1(mcar_TargetTagsvars_cat, mcar_imputedvars_cat, average ='macro' )
      df_total.loc[ind, 'mcar_f1_ord_'+str(k)]  = f1(mcar_TargetTagsvars_ord, mcar_imputedvars_ord, average ='macro' )
      df_total.loc[ind, 'mcar_rmse_int_'+str(k)]  = rmse(mcar_TargetTagsvars_int, mcar_imputedvars_int)

    if ind%20 == 0:
      print(f'Загружено {ind} из {data_mis.shape[0]}' )

    # if ind == 50: break

    df_stat = pd.concat([df_stat, df])

    df_stat_total = pd.concat([df_stat_total, df_total])
    df_vars_full = pd.concat([df_vars_full, df_vars])

    df_stat = df_stat.drop_duplicates()
    df_stat_total = df_stat_total.drop_duplicates()

    df_vars_full = df_vars_full.drop_duplicates()

  print(df_stat.shape)
  print(df_stat_total.shape)
  print(df_vars_full.shape)

Доля пропусков 1
--------------------------------------
--- 0.6916365623474121 seconds ---
--- 0.9382402896881104 seconds ---
--- 1.2094216346740723 seconds ---

<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error

--- 1.5064797401428223 seconds ---

<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error

--- 1.830186128616333 seconds ---

<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`

--- 2.115231513977051 seconds ---

<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error

--- 2.3469276428222656 seconds ---

<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:59: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:45: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error
<ipython-input-10-e1bcde65db0e>:52: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[ind, var+'_'+str(k)] = error

Загружено 0 из 1009
--- 0.18468379974365234 seconds ---
--- 0.4609053134918213 seconds ---
--- 0.9485070705413818 seconds ---
--- 1.2595899105072021 seconds ---
--- 1.5460741519927979 seconds ---
--- 1.8473284244537354 seconds ---
--- 2.2407100200653076 seconds ---
--- 0.05163764953613281 seconds ---
--- 0.24236178398132324 seconds ---
--- 0.422910213470459 seconds ---
--- 0.6224262714385986 seconds ---
--- 0.8121330738067627 seconds ---
--- 0.9903161525726318 seconds ---
--- 1.1767849922180176 seconds ---
--- 0.053050994873046875 seconds ---
--- 0.23229026794433594 seconds ---
--- 0.42594122886657715 seconds ---
--- 0.6247289180755615 seconds ---
--- 0.8065199851989746 seconds ---
--- 0.9801867008209229 seconds ---
--- 1.1550319194793701 seconds ---
--- 0.05431675910949707 seconds ---
--- 0.23194122314453125 seconds ---
--- 0.4149513244628906 seconds ---
--- 0.5981707572937012 seconds ---
--- 0.791062593460083 seconds ---
--- 1.0234262943267822 seconds ---
--- 1.2684812545776367 seconds ---
--- 0.06669855117797852 seconds ---
--- 0.446155309677124 seconds ---
--- 0.7022593021392822 seconds ---
--- 1.0154132843017578 seconds ---
--- 1.2760341167449951 seconds ---
--- 1.5479152202606201 seconds ---
--- 1.8359498977661133 seconds ---
--- 0.05036139488220215 seconds ---
--- 0.23986601829528809 seconds ---
--- 0.450946569442749 seconds ---
--- 0.6310093402862549 seconds ---
--- 0.8118133544921875 seconds ---
--- 0.9971675872802734 seconds ---
--- 1.1885058879852295 seconds ---
--- 0.05607318878173828 seconds ---
--- 0.2391362190246582 seconds ---
--- 0.44213056564331055 seconds ---
--- 0.6183898448944092 seconds ---

KeyboardInterrupt:

In [ ]:
df_stat.to_excel('KNN_stat_part.xlsx')
df_stat_total.to_excel('KNN_stat_total.xlsx')
df_vars_full.to_excel('KNN_stat_var.xlsx')

In [ ]:
files.download('KNN_stat_part.xlsx')
files.download('KNN_stat_total.xlsx')
files.download('KNN_stat_var.xlsx')

# MICE

In [ ]:
! pip install  fancyimpute
import fancyimpute

Collecting fancyimpute
  Downloading fancyimpute-0.7.0.tar.gz (25 kB)
  Preparing metadata (setup.py) ... done
Collecting knnimpute>=0.1.0 (from fancyimpute)
  Downloading knnimpute-0.1.0.tar.gz (8.3 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: scikit-learn>=0.24.2 in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.6.1)
Requirement already satisfied: cvxpy in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.6.5)
Requirement already satisfied: cvxopt in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (1.3.2)
Requirement already satisfied: pytest in /usr/local/lib/python3.11/dist-packages (from fancyimpute) (8.3.5)
Collecting nose (from fancyimpute)
  Downloading nose-1.3.7-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: six in /usr/local/lib/python3.11/dist-packages (from knnimpute>=0.1.0->fancyimpute) (1.17.0)
Requirement already satisfied: numpy>=1.10 in /usr/local/lib/python3.11/dist-packages (from knnimpute>=0.1.0->fancyimpute) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.15.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.11/dist-packages (from scikit-learn>=0.24.2->fancyimpute) (3.6.0)
Requirement already satisfied: osqp>=0.6.2 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (1.0.3)
Requirement already satisfied: clarabel>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (0.10.0)
Requirement already satisfied: scs>=3.2.4.post1 in /usr/local/lib/python3.11/dist-packages (from cvxpy->fancyimpute) (3.2.7.post2)
Requirement already satisfied: iniconfig in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (2.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (24.2)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest->fancyimpute) (1.5.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.11/dist-packages (from osqp>=0.6.2->cvxpy->fancyimpute) (75.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->osqp>=0.6.2->cvxpy->fancyimpute) (3.0.2)
Downloading nose-1.3.7-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 9.9 MB/s eta 0:00:00
Building wheels for collected packages: fancyimpute, knnimpute
  Building wheel for fancyimpute (setup.py) ... done
  Created wheel for fancyimpute: filename=fancyimpute-0.7.0-py3-none-any.whl size=29879 sha256=3cd701b13d3d2be5317969a5a7eca3994164a19a77efcb62a9cc12c3c881d8d6
  Stored in directory: /root/.cache/pip/wheels/1a/f3/a1/f7f10b5ae2c2459398762a3fcf4ac18c325311c7e3163d5a15
  Building wheel for knnimpute (setup.py) ... done
  Created wheel for knnimpute: filename=knnimpute-0.1.0-py3-none-any.whl size=11331 sha256=12151f95068bc3d66c8df355fad47e9bf1a57ae015893ea8dc745ebc99098aec
  Stored in directory: /root/.cache/pip/wheels/ea/e8/e0/79872972161e54486517ae507f94b2c7cea27fb7ef793bd415
Successfully built fancyimpute knnimpute
Installing collected packages: nose, knnimpute, fancyimpute
Successfully installed fancyimpute-0.7.0 knnimpute-0.1.0 nose-1.3.7

In [ ]:
from fancyimpute import IterativeImputer
df = pd.DataFrame(dfm1)
def mice(df):
  # Initialize KNNImputer
  im_data = dfm1[dfm1.columns]


  mice_imputer = IterativeImputer()
  im_data = mice_imputer.fit_transform(im_data)

  # printing dataframe
  im_data = pd.DataFrame(im_data, columns=df.columns)

  return im_data

a = mice(df)
a.isna().sum().sum()

np.int64(0)

In [ ]:
df = pd.DataFrame()
df_total = pd.DataFrame()
df_stat = pd.DataFrame()
df_stat_total = pd.DataFrame()
df_vars = pd.DataFrame()
df_vars_full = pd.DataFrame()


for i in range(1, 6):
  print('Доля пропусков', i)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar_.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(data_mis.shape[0]):
    df.loc[ind, '%'] = i/10

    df_total.loc[ind, '%'] =  i/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)

    start_time = time.time()

    imp_data = mice(dfm1).reset_index(drop = True)
    print("--- %s seconds ---" % (time.time() - start_time))

    for var in dfm1.columns:
      # print('-------------------------', var)
      index_mis = list(map(int, dfm1[var][dfm1[var].isna()].index))
      mis_imput =  imp_data[var].loc[index_mis]
      tar_vals = dft1[var].loc[index_mis]
      if len(tar_vals) == 0:
        df[var] = 'full'
        continue
      else:
        if var in int_cols:
          error = rmse(tar_vals, mis_imput)
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = imp_data[var].var()

        if var in ord_cols:
          mis_imput = mis_imput.apply(lambda row: math.ceil(row))
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

        if var in cat_cols:
          mis_imput = mis_imput.apply(lambda row: math.ceil(row))
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

  # total metrics
    imputed_data = mice(dfm1).reset_index(drop = True)
    im_int = imputed_data[list(set(miss_vars) & set(int_cols))]
    im_ord = imputed_data[list(set(miss_vars) & set(ord_cols))].apply(np.ceil)
    im_cat = imputed_data[list(set(miss_vars) & set(cat_cols))].apply(np.ceil)


    im_cat_mar = imputed_data[mar_cat]
    im_cat_mcar = imputed_data[mcar_cat]

    im_ord_mar = imputed_data[mar_ord]
    im_ord_mcar = imputed_data[mcar_ord]

    im_int_mar = imputed_data[mar_int]
    im_int_mcar = imputed_data[mcar_int]

    imputedvars_int = np.array(im_int)[np.array(dfm1[miss_vars][int_cols].isna())]
    imputedvars_ord = np.array(im_ord)[np.array(dfm1[miss_vars][ord_cols].isna())]
    imputedvars_cat = np.array(im_cat)[np.array(dfm1[list(set(miss_vars) & set(cat_cols))].isna())]

    mar_imputedvars_cat = np.ceil(np.array(im_cat_mar)[np.array(dfm1[mar_cat].isna())])
    mar_imputedvars_ord = np.ceil(np.array(im_ord_mar)[np.array(dfm1[mar_ord].isna())])
    mar_imputedvars_int = np.array(im_int_mar)[np.array(dfm1[mar_int].isna())]
    mcar_imputedvars_cat = np.ceil(np.array(im_cat_mcar)[np.array(dfm1[mcar_cat].isna())])
    mcar_imputedvars_ord = np.ceil(np.array(im_ord_mcar)[np.array(dfm1[mcar_ord].isna())])
    mcar_imputedvars_int = np.array(im_int_mcar)[np.array(dfm1[mcar_int].isna())]


    TargetTagsvars_int = np.array(dft1[miss_vars][int_cols])[dfm1[miss_vars][int_cols].isna()]
    TargetTagsvars_ord = np.array(dft1[miss_vars][ord_cols])[dfm1[miss_vars][ord_cols].isna()]
    TargetTagsvars_cat = np.array(dft1[list(set(miss_vars) & set(cat_cols))])[dfm1[list(set(miss_vars) & set(cat_cols))].isna()]

    mar_TargetTagsvars_cat = np.ceil(np.array(dft1[mar_cat])[dfm1[mar_cat].isna()])
    mar_TargetTagsvars_ord = np.ceil(np.array(dft1[mar_ord])[dfm1[mar_ord].isna()])
    mar_TargetTagsvars_int = np.array(dft1[mar_int])[dfm1[mar_int].isna()]
    mcar_TargetTagsvars_cat = np.array(dft1[mcar_cat])[dfm1[mcar_cat].isna()]
    mcar_TargetTagsvars_ord = np.array(dft1[mcar_ord])[dfm1[mcar_ord].isna()]
    mcar_TargetTagsvars_int = np.array(dft1[mcar_int])[dfm1[mcar_int].isna()]


    df_total.loc[ind, 'total_rmse_int'] = rmse(TargetTagsvars_int, imputedvars_int)

    # df_total.loc[ind, 'total_rmse_ord'] = rmse(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_acc_ord'] = acc(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_f1_ord']  = f1(TargetTagsvars_ord, imputedvars_ord, average ='macro' )
    # df_total['total_pr_ord']  = pr(TargetTagsvars_ord, imputedvars_ord, average ='macro')
    # df_total['total_rc_ord'] = rc(TargetTagsvars_ord, imputedvars_ord, average ='macro')

    df_total.loc[ind, 'total_acc_cat'] = acc(TargetTagsvars_cat, imputedvars_cat)
    df_total.loc[ind, 'total_f1_cat'] = f1(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_pr_cat'] = pr(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_rc_cat'] = rc(TargetTagsvars_cat, imputedvars_cat, average ='macro')

    #mar
    df_total.loc[ind, 'mar_f1_cat']  = f1(mar_TargetTagsvars_cat, mar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mar_f1_ord']  = f1(mar_TargetTagsvars_ord, mar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mar_rmse_int']  = rmse(mar_TargetTagsvars_int, mar_imputedvars_int)
    #mcar
    df_total.loc[ind, 'mcar_f1_cat']  = f1(mcar_TargetTagsvars_cat, mcar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mcar_f1_ord']  = f1(mcar_TargetTagsvars_ord, mcar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mcar_rmse_int']  = rmse(mcar_TargetTagsvars_int, mcar_imputedvars_int)

    if ind%20 == 0:
      print(f'Загружено {ind} из {data_mis.shape[0]}' )

    # if ind == 50: break

    df_stat = pd.concat([df_stat, df])

    df_stat_total = pd.concat([df_stat_total, df_total])
    df_vars_full = pd.concat([df_vars_full, df_vars])

    df_stat = df_stat.drop_duplicates()
    df_stat_total = df_stat_total.drop_duplicates()

    df_vars_full = df_vars_full.drop_duplicates()

  print(df_stat.shape)
  print(df_stat_total.shape)
  print(df_vars_full.shape)

Доля пропусков 1
--------------------------------------

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

--- 11.261451721191406 seconds ---

/usr/local/lib/python3.11/dist-packages/sklearn/impute/_iterative.py:895: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

Загружено 0 из 1012
--- 1.0693943500518799 seconds ---
--- 0.7240333557128906 seconds ---

KeyboardInterrupt:

In [ ]:
from google.colab import files

In [ ]:
df_stat.to_excel('mice_stat_part2.xlsx')
df_stat_total.to_excel('mice_stat_total2.xlsx')
df_vars_full.to_excel('mice_stat_vars2.xlsx')


files.download('mice_stat_part2.xlsx')
files.download('mice_stat_total2.xlsx')
files.download('mice_stat_vars2.xlsx')

In [ ]:
df_stat

,%,agea,agewrk,change_sal,edu,fctr_succ1,fctr_succ2,fctr_succ3,fctr_succ4,gndr,...,mot6,mot7,mot8,mot9,num_crs,plcwrk,profwrk,sal,sat_wrk,title_wrk
0,0.1,0.428564,1.023252,0.273810,0.409524,0.127978,0.295451,0.246665,0.266202,full,...,1.180882e-01,0.207050,0.157044,2.000539e-01,0.294370,0.190062,0.340982,5225.885707,0.214210,0.485043
1,0.1,0.435163,0.532760,0.611290,0.649003,0.141601,0.135281,0.134221,0.194296,full,...,1.863647e-01,0.325732,0.133112,8.568140e-07,0.451216,0.368615,0.248677,11182.129585,0.202999,0.350298
2,0.1,0.481719,0.332082,0.311454,0.163333,0.232140,0.198224,0.000004,0.261284,full,...,4.592676e-07,0.201668,0.000002,2.260970e-01,0.312170,0.242147,0.309524,9369.188328,0.146957,0.490332
3,0.1,0.341375,0.464111,0.444444,0.444345,0.302982,0.199288,0.004653,0.004647,full,...,8.006980e-02,0.185704,0.193401,1.869153e-01,0.239359,0.246579,0.292088,5594.143283,0.004010,0.407828
4,0.1,0.473053,0.363699,0.333333,0.283333,0.186104,0.033742,0.081495,0.164635,full,...,1.470877e-01,0.266366,0.200905,1.932752e-01,0.285108,0.432545,0.277551,4499.219687,0.116326,0.394253
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1230,0.5,1.262211,0.896884,0.268116,0.299299,0.303524,0.303585,0.303076,0.165059,full,...,2.221788e-01,0.294749,0.259635,2.558105e-01,0.446720,0.483802,0.094129,10535.831028,0.250425,0.355540
1231,0.5,1.194593,1.258759,0.380228,0.349462,0.361620,0.279101,0.313008,0.293720,full,...,2.634683e-01,0.091484,0.334583,2.891187e-01,0.421444,0.875857,0.136609,32344.482967,0.311803,0.203842
1232,0.5,1.097251,0.952893,0.407937,0.511470,0.377961,0.250961,0.261269,0.253711,full,...,3.684532e-01,0.354414,0.289462,2.630959e-01,0.339720,0.763696,0.108758,10942.691431,0.352714,0.340194
1233,0.5,1.204116,1.743372,0.346135,0.409673,0.332784,0.272346,0.299505,0.310391,full,...,2.566155e-01,0.291574,0.218285,2.564711e-01,0.584686,0.686950,0.219176,48632.698815,0.291122,0.317437
1234,0.5,0.969148,1.774599,0.290110,0.275380,0.347885,0.352213,0.309184,0.055636,full,...,2.943555e-01,0.339624,0.231247,6.433550e-02,0.421815,0.418124,0.160208,11048.798758,0.059266,0.366579

# EM

In [ ]:
from datetime import datetime as dt
import numpy as np
from functools import reduce

In [ ]:
def impute_em(X, max_iter = 30, eps = 1e-08):
    '''(np.array, int, number) -> {str: np.array or int}

    Precondition: max_iter >= 1 and eps > 0

    Return the dictionary with five keys where:
    - Key 'mu' stores the mean estimate of the imputed data.
    - Key 'Sigma' stores the variance estimate of the imputed data.
    - Key 'X_imputed' stores the imputed data that is mutated from X using
      the EM algorithm.
    - Key 'C' stores the np.array that specifies the original missing entries
      of X.
    - Key 'iteration' stores the number of iteration used to compute
      'X_imputed' based on max_iter and eps specified.
    '''
    columns = X.columns
    X = np.array(X)

    nr, nc = X.shape # количество строк и столбцов
    C = np.isnan(X) == False

    # Collect M_i and O_i's
    one_to_nc = np.arange(1, nc + 1, step = 1)
    M = one_to_nc * (C == False) - 1
    O = one_to_nc * C - 1

    # генерация изначльных параметров выборки (среднее и дисперсия)
    Mu = np.nanmean(X, axis = 0)
    observed_rows = np.where(np.isnan(sum(X.T)) == False)[0]
    S = np.cov(X[observed_rows, ].T)
    if np.isnan(S).any():
        S = np.diag(np.nanvar(X, axis = 0))

    # Start updating
    Mu_tilde, S_tilde = {}, {}
    X_tilde = X.copy()
    no_conv = True
    iteration = 0
    while no_conv and iteration < max_iter:
        for i in range(nr):
            S_tilde[i] = np.zeros(nc ** 2).reshape(nc, nc)
            if set(O[i, ]) != set(one_to_nc - 1): # missing component exists
                M_i, O_i = M[i, ][M[i, ] != -1], O[i, ][O[i, ] != -1]
                S_MM = S[np.ix_(M_i, M_i)]
                S_MO = S[np.ix_(M_i, O_i)]
                S_OM = S_MO.T
                S_OO = S[np.ix_(O_i, O_i)]
                Mu_tilde[i] = Mu[np.ix_(M_i)] +\
                    S_MO @ np.linalg.pinv(S_OO) @(X_tilde[i, O_i] - Mu[np.ix_(O_i)])
                X_tilde[i, M_i] = Mu_tilde[i]
                S_MM_O = S_MM - S_MO @ np.linalg.pinv(S_OO) @ S_OM

                S_tilde[i][np.ix_(M_i, M_i)] = S_MM_O
        Mu_new = np.mean(X_tilde, axis = 0)
        S_new = np.cov(X_tilde.T, bias = 1) +\
            reduce(np.add, S_tilde.values()) / nr
        no_conv =\
            np.linalg.norm(Mu - Mu_new) >= eps or\
            np.linalg.norm(S - S_new, ord = 2) >= eps
        Mu = Mu_new
        S = S_new
        iteration += 1
        if iteration % 10 == 0:
          print('Iteration №', iteration)
    X_tilde = pd.DataFrame(X_tilde, columns = columns)
    result = {
        'mu': Mu,
        'Sigma': S,
        'X_imputed': X_tilde,
        'C': C,
        'iteration': iteration
    }

    return result

In [ ]:
df = pd.DataFrame()
df_total = pd.DataFrame()
df_stat = pd.DataFrame()
df_stat_total = pd.DataFrame()
df_vars = pd.DataFrame()
df_vars_full = pd.DataFrame()


for i in range(5, 6):
  print('Доля пропусков', i)
  print('--------------------------------------')
  file_mis = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_.json'
  file_tar = '/content/drive/MyDrive/Диплом/Датасеты/данные диплом/0'+str(i)+'/data0'+str(i) +'_tar_.json'

  data_mis = pd.read_json(file_mis)
  data_tar =  pd.read_json(file_tar)

  for ind in range(data_mis.shape[0]):
    df.loc[ind, '%'] = i/10

    df_total.loc[ind, '%'] =  i/10

    dfm1 = pd.DataFrame(data_mis.loc[ind].to_dict())
    dft1 = pd.DataFrame(data_tar.loc[ind].to_dict())

    dfm1 = dfm1[sorted(dfm1.columns)].reset_index(drop = True)
    dft1 = dft1[sorted(dfm1.columns)].reset_index(drop = True)
    start_time = time.time()

    imp_data_sl = impute_em(dfm1)
    imp_data = imp_data_sl['X_imputed'].reset_index(drop = True)
    print("--- %s seconds ---" % (time.time() - start_time))

    df.loc[ind, 'mu'] = str(imp_data_sl['mu'])
    df.loc[ind, 'sigma'] = str(imp_data_sl['Sigma'])

    for var in dfm1.columns:
      # print('-------------------------', var)
      index_mis = list(map(int, dfm1[var][dfm1[var].isna()].index))
      mis_imput =  imp_data[var].loc[index_mis]
      tar_vals = dft1[var].loc[index_mis]
      if len(tar_vals) == 0:
        df[var] = 'full'
        continue
      else:
        if var in int_cols:
          error = rmse(tar_vals, mis_imput)
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = imp_data[var].var()

        if var in ord_cols:
          mis_imput = mis_imput.apply(lambda row: math.ceil(row))
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

        if var in cat_cols:
          mis_imput = mis_imput.apply(lambda row: math.ceil(row))
          error = f1(tar_vals, mis_imput, average ='macro')
          df.loc[ind, var] = error
          # print(var, error)
          df_vars.loc[ind, var] = entropy(imp_data[var])

  # total metrics
    imputed_data = imp_data
    im_int = imputed_data[list(set(miss_vars) & set(int_cols))]
    im_ord = imputed_data[list(set(miss_vars) & set(ord_cols))].apply(np.ceil)
    im_cat = imputed_data[list(set(miss_vars) & set(cat_cols))].apply(np.ceil)


    im_cat_mar = imputed_data[mar_cat]
    im_cat_mcar = imputed_data[mcar_cat]

    im_ord_mar = imputed_data[mar_ord]
    im_ord_mcar = imputed_data[mcar_ord]

    im_int_mar = imputed_data[mar_int]
    im_int_mcar = imputed_data[mcar_int]

    imputedvars_int = np.array(im_int)[np.array(dfm1[miss_vars][int_cols].isna())]
    imputedvars_ord = np.array(im_ord)[np.array(dfm1[miss_vars][ord_cols].isna())]
    imputedvars_cat = np.array(im_cat)[np.array(dfm1[list(set(miss_vars) & set(cat_cols))].isna())]

    mar_imputedvars_cat = np.ceil(np.array(im_cat_mar)[np.array(dfm1[mar_cat].isna())])
    mar_imputedvars_ord = np.ceil(np.array(im_ord_mar)[np.array(dfm1[mar_ord].isna())])
    mar_imputedvars_int = np.array(im_int_mar)[np.array(dfm1[mar_int].isna())]
    mcar_imputedvars_cat = np.ceil(np.array(im_cat_mcar)[np.array(dfm1[mcar_cat].isna())])
    mcar_imputedvars_ord = np.ceil(np.array(im_ord_mcar)[np.array(dfm1[mcar_ord].isna())])
    mcar_imputedvars_int = np.array(im_int_mcar)[np.array(dfm1[mcar_int].isna())]


    TargetTagsvars_int = np.array(dft1[miss_vars][int_cols])[dfm1[miss_vars][int_cols].isna()]
    TargetTagsvars_ord = np.array(dft1[miss_vars][ord_cols])[dfm1[miss_vars][ord_cols].isna()]
    TargetTagsvars_cat = np.array(dft1[list(set(miss_vars) & set(cat_cols))])[dfm1[list(set(miss_vars) & set(cat_cols))].isna()]

    mar_TargetTagsvars_cat = np.ceil(np.array(dft1[mar_cat])[dfm1[mar_cat].isna()])
    mar_TargetTagsvars_ord = np.ceil(np.array(dft1[mar_ord])[dfm1[mar_ord].isna()])
    mar_TargetTagsvars_int = np.array(dft1[mar_int])[dfm1[mar_int].isna()]
    mcar_TargetTagsvars_cat = np.array(dft1[mcar_cat])[dfm1[mcar_cat].isna()]
    mcar_TargetTagsvars_ord = np.array(dft1[mcar_ord])[dfm1[mcar_ord].isna()]
    mcar_TargetTagsvars_int = np.array(dft1[mcar_int])[dfm1[mcar_int].isna()]


    df_total.loc[ind, 'total_rmse_int'] = rmse(TargetTagsvars_int, imputedvars_int)

    # df_total.loc[ind, 'total_rmse_ord'] = rmse(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_acc_ord'] = acc(TargetTagsvars_ord, imputedvars_ord )
    df_total.loc[ind, 'total_f1_ord']  = f1(TargetTagsvars_ord, imputedvars_ord, average ='macro' )
    # df_total['total_pr_ord']  = pr(TargetTagsvars_ord, imputedvars_ord, average ='macro')
    # df_total['total_rc_ord'] = rc(TargetTagsvars_ord, imputedvars_ord, average ='macro')

    df_total.loc[ind, 'total_acc_cat'] = acc(TargetTagsvars_cat, imputedvars_cat)
    df_total.loc[ind, 'total_f1_cat'] = f1(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_pr_cat'] = pr(TargetTagsvars_cat, imputedvars_cat, average ='macro')
    # df_total['total_rc_cat'] = rc(TargetTagsvars_cat, imputedvars_cat, average ='macro')

    #mar
    df_total.loc[ind, 'mar_f1_cat']  = f1(mar_TargetTagsvars_cat, mar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mar_f1_ord']  = f1(mar_TargetTagsvars_ord, mar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mar_rmse_int']  = rmse(mar_TargetTagsvars_int, mar_imputedvars_int)
    #mcar
    df_total.loc[ind, 'mcar_f1_cat']  = f1(mcar_TargetTagsvars_cat, mcar_imputedvars_cat, average ='macro' )
    df_total.loc[ind, 'mcar_f1_ord']  = f1(mcar_TargetTagsvars_ord, mcar_imputedvars_ord, average ='macro' )
    df_total.loc[ind, 'mcar_rmse_int']  = rmse(mcar_TargetTagsvars_int, mcar_imputedvars_int)

    if ind%20 == 0:
      print(f'Загружено {ind} из {data_mis.shape[0]}' )

    # if ind == 50: break

    df_stat = pd.concat([df_stat, df])

    df_stat_total = pd.concat([df_stat_total, df_total])
    df_vars_full = pd.concat([df_vars_full, df_vars])

    df_stat = df_stat.drop_duplicates()
    df_stat_total = df_stat_total.drop_duplicates()

    df_vars_full = df_vars_full.drop_duplicates()

  print(df_stat.shape)
  print(df_stat_total.shape)
  print(df_vars_full.shape)

Доля пропусков 5
--------------------------------------

/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:557: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
<ipython-input-17-749b20698dc0>:30: RuntimeWarning: Degrees of freedom <= 0 for slice
  S = np.cov(X[observed_rows, ].T)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

Iteration № 10
Iteration № 20
Iteration № 30
--- 8.70658540725708 seconds ---
Загружено 0 из 1011

/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:557: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/usr/local/lib/python3.11/dist-packages/numpy/_core/_methods.py:130: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
<ipython-input-17-749b20698dc0>:30: RuntimeWarning: Degrees of freedom <= 0 for slice
  S = np.cov(X[observed_rows, ].T)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/usr/local/lib/python3.11/dist-packages/numpy/lib/_function_base_impl.py:2773: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)

KeyboardInterrupt:

In [ ]:
from google.colab import files

In [ ]:
df_stat.to_excel('EM_stat_part5_часть2.xlsx')
df_stat_total.to_excel('EM_stat_total5_часть2.xlsx')
df_vars_full.to_excel('EM_stat_var5_часть2.xlsx')


files.download('EM_stat_part5_часть2.xlsx')
files.download('EM_stat_total5_часть2.xlsx')
files.download('EM_stat_var5_часть2.xlsx')